//! Offline reverse geocoding -- the `mma-geocode` crate over the packed GeoNames table
//! `data/cities.bin` (generated by `scripts/gen-cities-bin.mjs`).

use mma_geocode::Geocoder;
use serde::Serialize;
use std::sync::OnceLock;

#[repr(align(4))]
struct Aligned<B: ?Sized>(B);
static TABLE: &Aligned<[u8]> = &Aligned(*include_bytes!("../../data/cities.bin"));

fn geocoder() -> &'static Geocoder<'static> {
    static GEOCODER: OnceLock<Geocoder<'static>> = OnceLock::new();
    GEOCODER.get_or_init(|| Geocoder::new(&TABLE.0).expect("cities.bin: invalid table"))
}

/// Reverse geocode result: nearest populated place to a coordinate.
#[derive(Serialize, specta::Type)]
pub struct GeoResult {
    pub city: String,
    /// First-level administrative division (state, province, region).
    pub admin: String,
    pub country: String,
    /// ISO 3166-1 alpha-2 (e.g. "US", "FR").
    pub country_code: String,
}

/// Validate the table's header ahead of the first lookup.
pub fn warm() {
    geocoder();
}

/// Return the nearest city, administrative region, and country for a coordinate.
/// Always returns `Some` - the dataset covers every landmass.
#[tauri::command]
#[specta::specta]
pub fn reverse_geocode(lat: f64, lng: f64) -> Option<GeoResult> {
    geocoder().nearest(lat, lng).map(|r| GeoResult {
        city: r.name,
        admin: r.admin1.to_string(),
        country: r.country_code.to_string(),
        country_code: r.country_code.to_string(),
    })
}
