pub(crate) mod feedback;
pub(crate) mod gdoc;
pub(crate) mod geocoder;
pub(crate) mod geoguessr;
pub(crate) mod github;
pub(crate) mod presence;
pub(crate) mod proxy;
pub(crate) mod remote_api;
#[cfg(feature = "web-serve")]
pub mod serve;
pub(crate) mod update;
