[package]
name = "vali-generate"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
anyhow = "1"
bzip2 = "0.6.1"
fastrand = "2"
geojson = "0.24"
mma-geo = { path = "../../geo" }
percent-encoding = "2.3"
rayon = "1"
rust_decimal = "1"
rustc-hash = "2"
serde = { features = ["derive"], version = "1" }
serde_json = { features = ["float_roundtrip"], version = "1" }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json", "rustls-no-provider"] }
vali-core = { path = "../vali-core" }
vali-data = { path = "../vali-data" }
vali-expr = { path = "../vali-expr" }
vali-geo = { path = "../vali-geo" }
