// code generated by pbf v5.1.0

export function readRemoteLocationsResponse(pbf, end) {
    const obj = {tag: [], location: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.tag.push(pbf.readString());
        else if (field === 2) obj.location.push(readRemoteLocation(pbf, pbf.readVarint() + pbf.pos));
    }
    return obj;
}
export function writeRemoteLocationsResponse(obj, pbf) {
    if (obj.tag) for (const item of obj.tag) pbf.writeStringField(1, item);
    if (obj.location) for (const item of obj.location) pbf.writeMessage(2, writeRemoteLocation, item);
}

export function readRemoteLocation(pbf, end) {
    const obj = {id: 0, author: 0, location: undefined, panoId: "", heading: 0, pitch: 0, zoom: 0, tagIndex: [], flags: 0, createdAt: 0, panoDate: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.id = pbf.readVarint();
        else if (field === 2) obj.author = pbf.readVarint();
        else if (field === 3) obj.location = readRemoteLatLng(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 4) obj.panoId = pbf.readString();
        else if (field === 5) obj.heading = pbf.readDouble();
        else if (field === 6) obj.pitch = pbf.readDouble();
        else if (field === 7) obj.zoom = pbf.readDouble();
        else if (field === 8) pbf.readPackedVarint(obj.tagIndex);
        else if (field === 9) obj.flags = pbf.readVarint();
        else if (field === 10) obj.createdAt = pbf.readVarint();
        else if (field === 11) obj.panoDate = pbf.readVarint();
    }
    return obj;
}
export function writeRemoteLocation(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.author) pbf.writeVarintField(2, obj.author);
    if (obj.location) pbf.writeMessage(3, writeRemoteLatLng, obj.location);
    if (obj.panoId) pbf.writeStringField(4, obj.panoId);
    if (obj.heading) pbf.writeDoubleField(5, obj.heading);
    if (obj.pitch) pbf.writeDoubleField(6, obj.pitch);
    if (obj.zoom) pbf.writeDoubleField(7, obj.zoom);
    if (obj.tagIndex) pbf.writePackedVarint(8, obj.tagIndex);
    if (obj.flags) pbf.writeVarintField(9, obj.flags);
    if (obj.createdAt) pbf.writeVarintField(10, obj.createdAt);
    if (obj.panoDate) pbf.writeVarintField(11, obj.panoDate);
}

export function readRemoteLatLng(pbf, end) {
    const obj = {lat: 0, lng: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.lat = pbf.readDouble();
        else if (field === 2) obj.lng = pbf.readDouble();
    }
    return obj;
}
export function writeRemoteLatLng(obj, pbf) {
    if (obj.lat) pbf.writeDoubleField(1, obj.lat);
    if (obj.lng) pbf.writeDoubleField(2, obj.lng);
}
