// Generated by `npm run gen:bindings`. Do not edit.
// No imports, ever: procedures bundle this file and must not reach Tauri.

export const CameraType = {
	/** First-generation Street View camera. */
	Gen1: "gen1",
	/** Second- or third-generation camera. */
	Gen2: "gen2",
	/** Fourth-generation camera. */
	Gen4: "gen4",
	/** A capture from a known bad camera. */
	Badcam: "badcam",
	/** An indoor capture from a tripod. */
	Tripod: "tripod",
	/** A special collect carried on foot or on another vehicle, such as a trekker. */
	Trekker: "trekker",
} as const;
export type CameraType = (typeof CameraType)[keyof typeof CameraType];

/** A calendar component to group dates by. */
export const DatePart = {
	/** The calendar year. */
	Year: "year",
	/** The year and month. */
	YearMonth: "yearMonth",
	/** The calendar date. */
	Day: "day",
	/** The month, the same in every year. */
	MonthOfYear: "monthOfYear",
	/** The hour of the day. */
	HourOfDay: "hourOfDay",
} as const;
export type DatePart = (typeof DatePart)[keyof typeof DatePart];

/**
 * Type discriminant for `Location.extra` field definitions.
 * Determines how the field is displayed and filtered in the UI.
 */
export const ExtraFieldType = {
	/** Text. */
	String: "string",
	/** A number. */
	Number: "number",
	/** A point in time. */
	Date: "date",
	/** A year and month. */
	Month: "month",
	/** One of a fixed set of values. */
	Enum: "enum",
	/** A list of values. */
	Array: "array",
} as const;
export type ExtraFieldType = (typeof ExtraFieldType)[keyof typeof ExtraFieldType];

/**
 * First-sync seeding when both sides already have pins. Only meaningful on the first sync
 * (empty mapping); afterwards it's plain three-way. `Merge` never deletes.
 */
export const FirstSyncMode = {
	/** Both maps keep everything; nothing is deleted. */
	Merge: "merge",
	/** Locations only on this map are deleted so it matches the remote map. */
	MirrorFromRemote: "mirrorFromRemote",
	/** Locations only on the remote map are deleted so it matches this map. */
	MirrorFromLocal: "mirrorFromLocal",
} as const;
export type FirstSyncMode = (typeof FirstSyncMode)[keyof typeof FirstSyncMode];

export const IssueState = {
	/** The issue is still open. */
	Open: "open",
	/** The issue has been closed. */
	Closed: "closed",
} as const;
export type IssueState = (typeof IssueState)[keyof typeof IssueState];

/** When a move target already holds a value, which side survives. */
export const MergeWinner = {
	/** The moved value replaces what the target already holds. */
	From: "from",
	/** The target keeps its own value and the moved value is dropped. */
	To: "to",
} as const;
export type MergeWinner = (typeof MergeWinner)[keyof typeof MergeWinner];

/**
 * What one attempt charges the bucket: the call itself, or one per row in its batch
 * (for APIs that bill multi-row requests per row).
 */
export const RateCost = {
	/** Each attempt charges the rate limit once, however many rows it carries. */
	Request: "request",
	/** Each attempt charges the rate limit once per row it carries; a query carries no rows and charges once. */
	Row: "row",
} as const;
export type RateCost = (typeof RateCost)[keyof typeof RateCost];

/** Which side won a resolved conflict. */
export const ResolutionSide = {
	/** This map's version won the conflict. */
	Local: "local",
	/** The remote map's version won the conflict. */
	Remote: "remote",
} as const;
export type ResolutionSide = (typeof ResolutionSide)[keyof typeof ResolutionSide];

/**
 * Where a provider's results go. `Patch` applies them to the locations they name;
 * `Collect` delivers them to the caller and writes nothing. The declaration decides
 * this, never the contents of a result.
 */
export const Sink = {
	/** Results are written to the locations they name. */
	Patch: "patch",
	/** Results are handed back and nothing is written. */
	Collect: "collect",
} as const;
export type Sink = (typeof Sink)[keyof typeof Sink];

/** Per-location bitfield, serialized as a plain `u32` over IPC and Arrow. */
export const LocationFlag = {
	/** No flags set. */
	None: 0,
	/** When the location has a stored pano, it opens exactly that pano instead of the nearest coverage. */
	LoadAsPanoId: 1,
	/** Legacy marker (web). Kept as imported, with no effect in the app. */
	Informational: 2,
	/** A location from a pending import, opened for preview and not yet on the map. */
	ImportPreview: 4,
	/** A pano opened from the seen history overlay, not yet on the map. */
	SeenOverlay: 8,
} as const;
export type LocationFlag = (typeof LocationFlag)[keyof typeof LocationFlag];

/** Which imagery collection a pano id belongs to. */
export const PanoType = {
	/** Official Street View coverage. */
	Official: 2,
	/** Unofficial imagery from outside the user-uploaded collection. */
	Unknown: 3,
	/** Imagery uploaded by users. */
	UserUploaded: 10,
} as const;
export type PanoType = (typeof PanoType)[keyof typeof PanoType];

/**
 * Which pano the search picks; omitted means closest. BEST at a small radius can return a
 * neighbouring pano from the same capture run, so probe a pano's own coordinate with CLOSEST.
 */
export const RankingStrategy = {
	/** The pano the search ranks best within the radius, which may not be the nearest. */
	Best: 1,
	/** The pano nearest the searched point, and the choice when none is given. */
	Closest: 2,
} as const;
export type RankingStrategy = (typeof RankingStrategy)[keyof typeof RankingStrategy];

/** Outcome of a Street View coverage check, as `validate` answers it per row. */
export const ValidationState = {
	/** The location's coverage checked out, with nothing to report. */
	Ok: 0,
	/** The location is pinned to a pano, and newer official coverage exists that it does not show. */
	UpdateAvailable: 1,
	/** Newer official coverage exists here, and the unpinned location already shows it. */
	UpdateApplied: 2,
	/** The location shows bad-camera coverage, but its timeline holds a better camera capture. */
	GoodcamAvailable: 6,
	/** The location's pinned pano no longer loads, though coverage still exists at its coordinates. */
	PanoIdBroke: 4,
	/** The coverage the location shows is unofficial. */
	Unofficial: 5,
	/** No coverage was found, neither the stored pano nor any within the search radius. */
	NotFound: 3,
} as const;
export type ValidationState = (typeof ValidationState)[keyof typeof ValidationState];

export const BUILTIN_FIELDS = [{"key":"lat","label":"Latitude","type":"number","kind":"identity","comparison":null},{"key":"lng","label":"Longitude","type":"number","kind":"identity","comparison":null},{"key":"heading","label":"Heading","type":"number","kind":"writable","comparison":{"type":"circular","period":360.0}},{"key":"pitch","label":"Pitch","type":"number","kind":"writable","comparison":null},{"key":"zoom","label":"Zoom","type":"number","kind":"writable","comparison":null},{"key":"id","label":"ID","type":"number","kind":"identity","comparison":null},{"key":"createdAt","label":"Created","type":"date","kind":null,"comparison":null},{"key":"modifiedAt","label":"Modified","type":"date","kind":null,"comparison":null},{"key":"panoId","label":"Pano ID","type":"string","kind":null,"comparison":null},{"key":"tagCount","label":"Tag count","type":"number","kind":"virtual","comparison":null},{"key":"loadAsPanoId","label":"Load as pano ID","type":"number","kind":"writable","comparison":null}] as const;

export const OFFICIAL_ID_PATTERN = "^[-_A-Za-z0-9]{21}[AQgw]$" as const;

export const CLEARABLE_BUILTINS = ["panoId"] as const;

export const EFFECT_CALLS = ["fetch","fetchMany","panos","sidecar"] as const;

export const PLAIN_CALLS = ["classify","progress","fail","emit","aborted"] as const;

export const DEFAULT_DUPLICATE_SCORE = "tagCount + has(panoId) + loadAsPanoId + (heading != 0)" as const;

export const KNOWN_FIELDS = [{"key":"altitude","type":"number","label":"Altitude","values":[],"labels":[],"circularPeriod":null,"defaultOff":false},{"key":"countryCode","type":"string","label":"Country code","values":[],"labels":[],"circularPeriod":null,"defaultOff":false},{"key":"cameraType","type":"enum","label":"Camera type","values":["gen1","gen2","gen4","badcam","tripod","trekker"],"labels":[["gen1","Gen 1"],["gen2","Gen 2/3"],["gen4","Gen 4"],["badcam","Bad cam"],["tripod","Tripod"],["trekker","Trekker"]],"circularPeriod":null,"defaultOff":false},{"key":"panoType","type":"enum","label":"Pano type","values":["2","3","10"],"labels":[["2","Official"],["3","Unknown"],["10","User uploaded"]],"circularPeriod":null,"defaultOff":false},{"key":"imageDate","type":"month","label":"Image date","values":[],"labels":[],"circularPeriod":null,"defaultOff":false},{"key":"datetime","type":"date","label":"Exact date","values":[],"labels":[],"circularPeriod":null,"defaultOff":true},{"key":"timezone","type":"enum","label":"Timezone","values":[],"labels":[],"circularPeriod":null,"defaultOff":true},{"key":"drivingDirection","type":"number","label":"Driving direction","values":[],"labels":[],"circularPeriod":360.0,"defaultOff":true},{"key":"uploaderName","type":"string","label":"Uploader","values":[],"labels":[],"circularPeriod":null,"defaultOff":true},{"key":"coverageDates","type":"array","label":"Coverage dates","values":[],"labels":[],"circularPeriod":null,"defaultOff":true},{"key":"subdivision","type":"string","label":"Subdivision","values":[],"labels":[],"circularPeriod":null,"defaultOff":true}] as const;

export const PROJECTIONS = [{"id":"value","appliesTo":["string","enum","number","month"],"needsTz":false},{"id":"year","appliesTo":["date","month"],"needsTz":true},{"id":"yearMonth","appliesTo":["date"],"needsTz":true},{"id":"day","appliesTo":["date"],"needsTz":true},{"id":"monthOfYear","appliesTo":["date","month"],"needsTz":true},{"id":"hourOfDay","appliesTo":["date"],"needsTz":true}] as const;

export const SCRATCH_MAP_ID = "scratch" as const;

export const ERROR_CODES = ["auth","attachment-not-staged","attachment-too-large","attachment-not-image","upload-rejected","report-rejected","report-unreadable","sign-in-timed-out","sign-in-token-rejected","issue-rejected","geoguessr-polygonal","geoguessr-draft-too-large"] as const;

/** The bits a preview carries that a real location must not. */
export const VIRTUAL_FLAGS = 12 as const;
