// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Write arbitrary text content to a named temp file (`mma_{name}`). Returns the path.
	 *  Used by JS to pass large payloads via file instead of IPC serialization.
	 */
	writeTempFile: (name: string, content: string) => __TAURI_INVOKE<string>("write_temp_file", { name, content }),
	/**  Read a file from disk as UTF-8 text. Used by JS to read temp files and plugin sources. */
	readFile: (path: string) => __TAURI_INVOKE<string>("read_file", { path }),
	appReady: () => __TAURI_INVOKE<number>("app_ready"),
	/**  Return the platform-specific app data directory path (e.g., `%LOCALAPPDATA%/app.map-making.local`). */
	getAppDataDir: () => __TAURI_INVOKE<string>("get_app_data_dir"),
	/**  Report where map data is currently stored. */
	getDataLocation: () => __TAURI_INVOKE<DataLocation>("get_data_location"),
	/**
	 *  Set (`Some`) or clear (`None`) the data-folder override. Takes effect after relaunch.
	 *  Does not move existing data -- the caller warns the user.
	 */
	setDataLocation: (path: string | null) => __TAURI_INVOKE<null>("set_data_location", { path }),
	/**  Open the app data directory in the OS file explorer. */
	openDataFolder: () => __TAURI_INVOKE<null>("open_data_folder"),
	/**  Open the current log file in the OS default handler. */
	openLogFile: () => __TAURI_INVOKE<null>("open_log_file"),
	/**  Scan the `plugins/` directory under app data and return manifests for all installed plugins. */
	listUserPlugins: () => __TAURI_INVOKE<PluginManifest[]>("list_user_plugins"),
	/**
	 *  Download a plugin from the GitHub plugin repository and install it to the local plugins directory.
	 *  Fetches `manifest.json` and the main JS file specified in the manifest.
	 */
	installPlugin: (id: string) => __TAURI_INVOKE<PluginManifest>("install_plugin", { id }),
	/**  Remove a plugin by deleting its directory from the local plugins folder. */
	uninstallPlugin: (id: string) => __TAURI_INVOKE<null>("uninstall_plugin", { id }),
	/**
	 *  Download a plugin's sidecar bundle from GitHub Releases and extract it under
	 *  `{appData}/plugins/{plugin_id}/sidecar/`. Emits `sidecar-install-progress`.
	 */
	sidecarInstall: (pluginId: string, name: string, version: string) => __TAURI_INVOKE<null>("sidecar_install", { pluginId, name, version }),
	/**  Installed sidecar version for a plugin (from `sidecar/version.txt`), or `None`. */
	sidecarInstalledVersion: (pluginId: string) => __TAURI_INVOKE<string | null>("sidecar_installed_version", { pluginId }),
	/**
	 *  Spawn a plugin's installed sidecar binary. Streams stdout/stderr lines as
	 *  `sidecar-stdout` / `sidecar-stderr` events and the exit as `sidecar-exit`,
	 *  keyed by the returned run id. Runs in the sidecar dir so co-located dlls resolve.
	 */
	sidecarSpawn: (pluginId: string, name: string, args: string[]) => __TAURI_INVOKE<number>("sidecar_spawn", { pluginId, name, args }),
	/**  Kill a running sidecar process by run id (no-op if already exited). */
	sidecarKill: (runId: number) => __TAURI_INVOKE<null>("sidecar_kill", { runId }),
	checkBorderFile: (level: string) => __TAURI_INVOKE<boolean>("check_border_file", { level }),
	downloadBorderFile: (level: string) => __TAURI_INVOKE<null>("download_border_file", { level }),
	borderLookup: (lat: number, lng: number, level: string) => __TAURI_INVOKE<PolygonGeometry | null>("border_lookup", { lat, lng, level }).then((v) => (v==null?v:({...v,coordinates:v.coordinates.map(i=>i.map(i=>i.map(i=>i))),extraPolygons:v.extraPolygons==null?v.extraPolygons:v.extraPolygons.map(i=>i.map(i=>i.map(i=>i.map(i=>i))))}) as typeof v)),
	/**
	 *  Finds the nearest city/country for a coordinate. O(log n) k-d tree lookup.
	 *  Always returns `Some` -- the GeoNames dataset covers every landmass.
	 */
	reverseGeocode: (lat: number, lng: number) => __TAURI_INVOKE<GeoResult | null>("reverse_geocode", { lat, lng }),
	discordPresenceSet: (activity: PresenceActivity) => __TAURI_INVOKE<null>("discord_presence_set", { activity }),
	discordPresenceClear: () => __TAURI_INVOKE<null>("discord_presence_clear"),
	/**
	 *  Start (or re-key) the remote API server. Idempotent: a running server just
	 *  picks up the new key. Returns the base URL.
	 */
	remoteApiStart: (key: string) => __TAURI_INVOKE<string>("remote_api_start", { key }),
	remoteApiStop: () => __TAURI_INVOKE<null>("remote_api_stop"),
	/**
	 *  Webview -> HTTP reply path: resolves the parked request for `id`.
	 *  `payload` is JSON text, not a typed value -- specta cannot export the
	 *  recursive `serde_json::Value` type (stack overflow at bindings export).
	 */
	remoteApiRespond: (id: number, ok: boolean, payload: string) => __TAURI_INVOKE<void>("remote_api_respond", { id, ok, payload }),
	/**
	 *  Load a map's Arrow data from disk, rebuild all indexes, and return initial state
	 *  (tag counts, undo/redo availability). Must be called before any other store commands.
	 */
	storeOpenMap: (mapId: string) => __TAURI_INVOKE<StoreStatus>("store_open_map", { mapId }),
	/**
	 *  Close the current map: bake overlay, flush Arrow + tags + edit history to disk, then
	 *  release all in-memory state (batch, mmap, indexes, selections, undo stacks).
	 */
	storeCloseMap: () => __TAURI_INVOKE<null>("store_close_map"),
	/**  Autosave uncommitted changes to the delta sidecar. No-op when nothing changed. */
	storeSaveDirty: () => __TAURI_INVOKE<SaveResult>("store_save_dirty"),
	/**
	 *  Copy locations into another map, skipping ones the target already has. Tags and extra
	 *  fields carry over.
	 */
	storeCopyLocationsToMap: (targetMapId: string, ids: number[]) => __TAURI_INVOKE<CopyToMapResult>("store_copy_locations_to_map", { targetMapId, ids }),
	/**  Lightweight status query: location count, version, and dirty flag. */
	storeGetSummary: () => __TAURI_INVOKE<SummaryResult>("store_get_summary"),
	/**  Return metadata for every map in the database. */
	storeListMaps: () => __TAURI_INVOKE<MapMeta[]>("store_list_maps").then((v) => (v.map(i=>({...i,extra:({...i.extra,fields:i.extra.fields==null?i.extra.fields:Object.fromEntries(Object.entries(i.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})) as typeof v)),
	/**  Fetch a single map's metadata by ID. Returns `None` if not found. */
	storeGetMap: (id: string) => __TAURI_INVOKE<MapData | null>("store_get_map", { id }).then((v) => (v==null?v:({...v,meta:({...v.meta,extra:({...v.meta.extra,fields:v.meta.extra.fields==null?v.meta.extra.fields:Object.fromEntries(Object.entries(v.meta.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})}) as typeof v)),
	/**
	 *  Create a new empty map with default settings. Returns the full metadata
	 *  (including the generated UUID) so the frontend can navigate to it immediately.
	 */
	storeCreateMap: (name: string, folder: string | null) => __TAURI_INVOKE<MapData>("store_create_map", { name, folder }).then((v) => (({...v,meta:({...v.meta,extra:({...v.meta.extra,fields:v.meta.extra.fields==null?v.meta.extra.fields:Object.fromEntries(Object.entries(v.meta.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})}) as typeof v)),
	/**  Delete a map and all its data: database rows and files on disk. */
	storeDeleteMap: (id: string) => __TAURI_INVOKE<null>("store_delete_map", { id }),
	/**  Apply a partial update to a map's metadata; `None` fields are left unchanged. */
	storeUpdateMapMeta: (id: string, patch: MapMetaPatch_Deserialize) => __TAURI_INVOKE<null>("store_update_map_meta", { id, patch: ({...patch,scoreBounds:patch.scoreBounds==null?patch.scoreBounds:patch.scoreBounds,extra:patch.extra==null?patch.extra:({...patch.extra,fields:patch.extra.fields==null?patch.extra.fields:Object.fromEntries(Object.entries(patch.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) }),
	/**
	 *  Update `last_opened_at` to the current timestamp. Used to sort the map
	 *  list by recency in the dashboard.
	 */
	storeTouchMapOpened: (mapId: string) => __TAURI_INVOKE<null>("store_touch_map_opened", { mapId }),
	/**  Rename a folder across all maps that reference it. */
	storeRenameFolder: (from: string, to: string) => __TAURI_INVOKE<null>("store_rename_folder", { from, to }),
	/**  Delete a folder by setting all its maps' folder to `NULL` (moves them to root). */
	storeDeleteFolder: (name: string) => __TAURI_INVOKE<null>("store_delete_folder", { name }),
	/**  List all user-created tables with their row counts. Excludes SQLite internals. */
	storeDbTableInfo: () => __TAURI_INVOKE<DbTableInfo[]>("store_db_table_info"),
	/**
	 *  Add new locations. IDs are allocated server-side (monotonic). Records an undo entry
	 *  and clears the redo stack.
	 */
	storeAddLocations: (locations: Location[]) => __TAURI_INVOKE<MutationResult>("store_add_locations", { locations: locations.map(i=>i) }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**  Remove locations by ID. Snapshots the full location data for undo before deleting. */
	storeRemoveLocations: (ids: number[]) => __TAURI_INVOKE<MutationResult>("store_remove_locations", { ids }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Apply partial patches to existing locations. `record_undo` defaults to true;
	 *  set to false for ephemeral updates (e.g., plugin-driven batch modifications
	 *  that manage their own undo).
	 */
	storeUpdateLocations: (updates: Update<LocationPatch_Deserialize>[], recordUndo: boolean | null) => __TAURI_INVOKE<MutationResult>("store_update_locations", { updates, recordUndo }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Set (or clear) the active location. Fire-and-forget from JS; no re-render triggered.
	 *  JS patches the cell buffer synchronously to hide/show the active marker.
	 */
	storeSetActive: (id: number | null) => __TAURI_INVOKE<null>("store_set_active", { id }),
	/**
	 *  Set the default marker color used by the render delta path. Fire-and-forget from JS;
	 *  the JS side recolors its cell buffers in place (no full rebuild).
	 */
	storeSetMarkerColor: (color: [number, number, number]) => __TAURI_INVOKE<null>("store_set_marker_color", { color }),
	/**  Fetch a single location by ID. Returns `None` if the ID is dead or doesn't exist. */
	storeGetLocation: (id: number) => __TAURI_INVOKE<Location | null>("store_get_location", { id }).then((v) => (v==null?v:v as typeof v)),
	/**  Fetch multiple locations by ID. Silently skips IDs that don't exist. */
	storeGetLocationsByIds: (ids: number[]) => __TAURI_INVOKE<Location[]>("store_get_locations_by_ids", { ids }).then((v) => (v.map(i=>i) as typeof v)),
	/**
	 *  Dump every alive location to a temp JSON file. Returns the file path.
	 *  Used by export and plugins that need the full dataset.
	 */
	storeGetAllLocations: () => __TAURI_INVOKE<string>("store_get_all_locations"),
	/**
	 *  Count locations by country (offline point-in-polygon). Returns unsorted (ISO-A2, count) pairs.
	 *  `level` selects border precision, falling back to "light" if unavailable.
	 */
	storeCountryDistribution: (level: string) => __TAURI_INVOKE<([string, number])[]>("store_country_distribution", { level }),
	/**
	 *  Compute the bounding box [west, south, east, north]. O(N).
	 *  When `selected_only` is true, restricts to the current selection.
	 */
	storeBounds: (selectedOnly: boolean) => __TAURI_INVOKE<[number, number, number, number] | null>("store_bounds", { selectedOnly }).then((v) => (v==null?v:v.map(i=>i) as typeof v)),
	/**  Find all locations within `radius_m` metres of (`lat`, `lng`). */
	storeFindNearby: (lat: number, lng: number, radiusM: number) => __TAURI_INVOKE<Location[]>("store_find_nearby", { lat, lng, radiusM }).then((v) => (v.map(i=>i) as typeof v)),
	/**
	 *  For each input point, whether any existing location lies within `radius_m` metres.
	 *  Bulk form so callers probing many coordinates (e.g. the map generator skipping
	 *  already-covered spots) pay one IPC round-trip, not one per point.
	 */
	storeNearAny: (lats: number[], lngs: number[], radiusM: number) => __TAURI_INVOKE<boolean[]>("store_near_any", { lats: lats.map(i=>i), lngs: lngs.map(i=>i), radiusM }),
	/**
	 *  Collect all distinct values for an `extra` field across all alive locations. O(N).
	 *  Used by the filter UI to populate dropdown options.
	 */
	storeExtraFieldValues: (field: string) => __TAURI_INVOKE<string[]>("store_extra_field_values", { field }),
	/**
	 *  Create tags by name. Deduplicates case-insensitively: if a tag with the same name
	 *  already exists, it is made visible instead of creating a duplicate.
	 */
	storeCreateTags: (names: string[]) => __TAURI_INVOKE<MutationResult>("store_create_tags", { names }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Rename and/or recolor tags in one batch. Renaming onto an existing name (case-insensitive)
	 *  merges the two tags.
	 */
	storeUpdateTags: (updates: Update<TagPatch>[]) => __TAURI_INVOKE<MutationResult>("store_update_tags", { updates }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Strip tags from all locations. Tags stay in `store.tags` with count=0 /
	 *  visible=false so undo can revive them. Returns MutationResult with `tags`.
	 */
	storeDeleteTags: (tagIds: number[]) => __TAURI_INVOKE<MutationResult>("store_delete_tags", { tagIds }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Persist tag ordering. `ordered_ids` specifies the desired order; each tag's
	 *  `order` field is set to its index in the list.
	 */
	storeReorderTags: (orderedIds: number[]) => __TAURI_INVOKE<MutationResult>("store_reorder_tags", { orderedIds }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**  Pop the undo stack and reverse the last edit. Pushes the entry onto the redo stack. */
	storeUndo: () => __TAURI_INVOKE<MutationResult>("store_undo").then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**  Pop the redo stack and replay the edit forward. Pushes the entry back onto undo. */
	storeRedo: () => __TAURI_INVOKE<MutationResult>("store_redo").then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**  Clear both undo and redo stacks. Called after a commit to start fresh. */
	storeResetUndo: () => __TAURI_INVOKE<null>("store_reset_undo"),
	/**  The uncommitted changes since the last commit -- the same changeset `store_commit` will record. */
	storeCommitDiff: () => __TAURI_INVOKE<[number, number, number]>("store_commit_diff"),
	/**
	 *  Replace all selections, resolve bitmasks against current data, and write a binary
	 *  patch file for JS to apply to the render overlay. Returns per-selection counts.
	 */
	storeSyncSelections: (sels: SelectionInput[]) => __TAURI_INVOKE<SelectionSync>("store_sync_selections", { sels }),
	/**  Return the union of all currently selected location IDs. */
	storeGetSelectedIdsList: () => __TAURI_INVOKE<number[]>("store_get_selected_ids_list"),
	/**
	 *  Pick an evenly spaced subset of the current selection. Exactly one of `target_count`
	 *  (thin to N, maximizing spacing) or `min_distance_m` (keep as many as fit at that spacing)
	 *  must be provided.
	 */
	storePickSpaced: (targetCount: number | null, minDistanceM: number | null) => __TAURI_INVOKE<SpacedPickResult>("store_pick_spaced", { targetCount, minDistanceM }),
	/**
	 *  Resolve a single selection to its matching location IDs without persisting it.
	 *  Used by plugins and one-off queries (e.g., tag merge, export filtered).
	 */
	storeResolveSelection: (props: SelectionProps) => __TAURI_INVOKE<number[]>("store_resolve_selection", { props }),
	/**
	 *  Group locations by a derived key, returning `{ key, ids, bin }` per group.
	 *  `scope` restricts to a selection; `None` partitions the whole map.
	 */
	storePartition: (field: string, key: KeySpec, scope: Scope) => __TAURI_INVOKE<PartitionBucket[]>("store_partition", { field, key, scope }).then((v) => (v.map(i=>({...i,bin:i.bin==null?i.bin:i.bin.map(i=>i)})) as typeof v)),
	/**
	 *  Transitive spatial duplicate groups (connected components, size >= 2) within `distance`
	 *  metres. Read-only; used to preview a merge. Returns groups of location IDs.
	 */
	storeDuplicateGroups: (distance: number) => __TAURI_INVOKE<number[][]>("store_duplicate_groups", { distance }),
	/**
	 *  Merge each duplicate group within `distance` metres into one survivor location, unioning
	 *  tags and extra fields. One undoable edit.
	 */
	storeMergeDuplicates: (distance: number) => __TAURI_INVOKE<MutationResult>("store_merge_duplicates", { distance }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Thin duplicates among `ids` within `distance` metres, keeping the best location per
	 *  cluster. Informational locations are never pruned. One undoable edit.
	 */
	storePruneDuplicates: (ids: number[], distance: number, keepTagIds: number[]) => __TAURI_INVOKE<MutationResult>("store_prune_duplicates", { ids, distance, keepTagIds }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**
	 *  Full render rebuild: single-pass over all alive locations, writes binary to a temp file.
	 *  Returns the file path for JS to fetch via `mma-buf://`. Only called on map open or full reset.
	 */
	storeFillRenderFile: (req: RenderRequest) => __TAURI_INVOKE<string>("store_fill_render_file", { req }),
	/**
	 *  Resolve a deck.gl pick result (cell key + index within cell) to a location ID.
	 *  Called on marker click to map the GPU pick back to a logical location.
	 */
	storeResolvePick: (cell: string, cellIndex: number) => __TAURI_INVOKE<number | null>("store_resolve_pick", { cell, cellIndex }),
	/**
	 *  Parse a file (JSON or ZIP of JSONs) and return previews without persisting.
	 *  Results are cached in `CACHED_PARSE` so `bulk_import_confirm` can skip re-parsing.
	 *  ZIP files have each `.json` entry parsed in parallel via rayon.
	 */
	bulkImportPreview: (path: string) => __TAURI_INVOKE<ImportPreviewEntry[]>("bulk_import_preview", { path }),
	/**  Import the selected maps from a previously previewed file. Emits `bulk-import-progress` per map. */
	bulkImportConfirm: (path: string, selectedIndices: number[]) => __TAURI_INVOKE<ImportedMapInfo[]>("bulk_import_confirm", { path, selectedIndices }),
	/**
	 *  Drop the cached parse from `bulk_import_preview` when the user dismisses the
	 *  import dialog without confirming, instead of holding it until the next preview.
	 */
	bulkImportCancel: () => __TAURI_INVOKE<null>("bulk_import_cancel"),
	/**
	 *  Parse a file and return field-level statistics + preview positions for the editor
	 *  import sidebar. Caches the parse result for `store_import_file` to consume on commit.
	 */
	storeImportPreview: (path: string) => __TAURI_INVOKE<EditorImportPreview>("store_import_preview", { path }).then((v) => (({...v,bounds:v.bounds==null?v.bounds:v.bounds.map(i=>i)}) as typeof v)),
	/**
	 *  Parse pasted text (JSON or CSV) and stage it for preview, exactly like
	 *  `store_import_preview` does for a file. Caches the parse for `store_import_file`.
	 */
	storeImportPastePreview: (text: string) => __TAURI_INVOKE<EditorImportPreview>("store_import_paste_preview", { text }).then((v) => (({...v,bounds:v.bounds==null?v.bounds:v.bounds.map(i=>i)}) as typeof v)),
	/**
	 *  Fetch one staged (not yet imported) location by its preview index, for read-only
	 *  preview in the editor. Indexes follow the preview positions order.
	 */
	storeImportStagedLocation: (index: number) => __TAURI_INVOKE<Location>("store_import_staged_location", { index }),
	/**
	 *  Commit a previously previewed editor import, optionally dropping fields and/or
	 *  applying a bulk tag to every imported location. Consumes the cached parse from
	 *  `store_import_preview`/`store_import_paste_preview`. Fields in `dropped_fields`
	 *  (e.g. `"heading"`, `"extra.countryCode"`) are zeroed/removed.
	 */
	storeImportFile: (droppedFields: string[], tagName: string | null) => __TAURI_INVOKE<EditorImportResult>("store_import_file", { droppedFields, tagName }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),newFieldDefs:v.newFieldDefs==null?v.newFieldDefs:Object.fromEntries(Object.entries(v.newFieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))}) as typeof v)),
	/**  Export locations as a `{name, customCoordinates}` JSON file, including tags and field defs. */
	storeExportJson: (opts: ExportOpts) => __TAURI_INVOKE<string>("store_export_json", { opts }),
	/**  Export locations as a minimal lat/lng CSV file. */
	storeExportCsv: (scope: number[] | null) => __TAURI_INVOKE<string>("store_export_csv", { scope }),
	/**
	 *  Export locations as a GeoJSON FeatureCollection of Point features.
	 *  Each feature carries its tag names in `properties.tags`.
	 */
	storeExportGeojson: (scope: number[] | null, tagsJson: string) => __TAURI_INVOKE<string>("store_export_geojson", { scope, tagsJson }),
	/**
	 *  Copy a temp export file to the destination chosen via the native save dialog,
	 *  then remove the temp source. `dest_path` comes from the frontend save dialog.
	 */
	storeSaveExportFile: (srcPath: string, destPath: string) => __TAURI_INVOKE<null>("store_save_export_file", { srcPath, destPath }),
	/**  Export every map in the database as a ZIP of JSON files. Duplicate map names get a numeric suffix. */
	storeExportBulkZip: () => __TAURI_INVOKE<string>("store_export_bulk_zip"),
	/**
	 *  Create a temp session dir for binary uploads from the frontend. Files are
	 *  written into it via `mma-buf://` POST, then packaged by [`store_upload_finish`].
	 */
	storeUploadBegin: () => __TAURI_INVOKE<string>("store_upload_begin"),
	/**
	 *  Package an upload session and remove its dir: a single file is moved out
	 *  as-is, multiple are packed into a Stored ZIP (entries like JPEG/PNG are
	 *  already compressed). Returns a temp path for [`store_save_export_file`].
	 */
	storeUploadFinish: (sessionDir: string) => __TAURI_INVOKE<string>("store_upload_finish", { sessionDir }),
	/**  Remove an abandoned upload session dir (e.g. cancelled operation). */
	storeUploadAbort: (sessionDir: string) => __TAURI_INVOKE<null>("store_upload_abort", { sessionDir }),
	/**
	 *  Delete all rows from a table. Returns the number of deleted rows.
	 *  Used in the debug panel for cache/history cleanup.
	 */
	storeDbClearTable: (table: string) => __TAURI_INVOKE<number>("store_db_clear_table", { table }),
	/**
	 *  Compute aggregate database statistics (map/location/tag/commit counts,
	 *  database file size, journal mode). Tag count is summed across all maps
	 *  by parsing each map's tags JSON column.
	 */
	storeDbStats: () => __TAURI_INVOKE<DbStats>("store_db_stats"),
	/**  Record a panorama visit. Oldest entries beyond `MAX_SEEN` are evicted. */
	storeSeenWrite: (entry: SeenWriteEntry) => __TAURI_INVOKE<null>("store_seen_write", { entry }),
	/**  Returns a page of seen entries, newest first, with optional filtering. */
	storeSeenList: (limit: number, offset: number, filter: SeenFilter | null, thumbnails: boolean) => __TAURI_INVOKE<SeenEntry[]>("store_seen_list", { limit, offset, filter, thumbnails }).then((v) => (v.map(i=>i) as typeof v)),
	/**  Returns the total number of seen entries matching the filter (for pagination). */
	storeSeenCount: (filter: SeenFilter | null) => __TAURI_INVOKE<number>("store_seen_count", { filter }),
	/**
	 *  Returns all distinct country codes present in the seen table, sorted alphabetically.
	 *  Used to populate the country filter dropdown.
	 */
	storeSeenCountries: () => __TAURI_INVOKE<string[]>("store_seen_countries"),
	/**
	 *  Returns all distinct maps that have seen entries, with resolved display names.
	 *  Returns maps that have seen entries. Only includes maps that still exist.
	 */
	storeSeenMaps: () => __TAURI_INVOKE<SeenMapInfo[]>("store_seen_maps"),
	/**  Deletes all seen history entries. */
	storeSeenClear: () => __TAURI_INVOKE<null>("store_seen_clear"),
	storeReviewCreate: (session: ReviewCreate) => __TAURI_INVOKE<ReviewSession>("store_review_create", { session }),
	storeReviewGet: (mapId: string, sourceKey: string) => __TAURI_INVOKE<ReviewSession | null>("store_review_get", { mapId, sourceKey }),
	storeReviewList: (mapId: string, status: string | null) => __TAURI_INVOKE<ReviewSession[]>("store_review_list", { mapId, status }),
	storeReviewUpdate: (update: ReviewUpdate) => __TAURI_INVOKE<null>("store_review_update", { update }),
	storeReviewDelete: (id: string) => __TAURI_INVOKE<null>("store_review_delete", { id }),
	remoteMappingGet: (provider: string, mapId: string) => __TAURI_INVOKE<RemoteMappingRow[]>("remote_mapping_get", { provider, mapId }),
	remoteMappingUpsert: (provider: string, mapId: string, rows: RemoteMappingRow[]) => __TAURI_INVOKE<null>("remote_mapping_upsert", { provider, mapId, rows }),
	remoteMappingDelete: (provider: string, mapId: string, localIds: number[]) => __TAURI_INVOKE<null>("remote_mapping_delete", { provider, mapId, localIds }),
	remoteMappingClear: (provider: string, mapId: string) => __TAURI_INVOKE<null>("remote_mapping_clear", { provider, mapId }),
	/**
	 *  Reconcile a linked, open map against its remote. Snapshots local state under the store lock,
	 *  drops the lock, then does all network + persistence off the async thread.
	 */
	syncReconcile: (provider: string, mapId: string, remoteMapId: string, apiKey: string | null, firstSync: FirstSyncMode | null, resolutions: ([string, ResolutionSide])[] | null) => __TAURI_INVOKE<SyncReconcileResult>("sync_reconcile", { provider, mapId, remoteMapId, apiKey, firstSync, resolutions }).then((v) => (({...v,conflicts:v.conflicts.map(i=>({...i,local:i.local==null?i.local:i.local,remote:i.remote==null?i.remote:i.remote})),pullUpdates:v.pullUpdates.map(i=>({...i,patch:({...i.patch,lat:i.patch.lat==null?i.patch.lat:i.patch.lat,lng:i.patch.lng==null?i.patch.lng:i.patch.lng,heading:i.patch.heading==null?i.patch.heading:i.patch.heading,pitch:i.patch.pitch==null?i.patch.pitch:i.patch.pitch,zoom:i.patch.zoom==null?i.patch.zoom:i.patch.zoom})}))}) as typeof v)),
	/**
	 *  Open the GeoGuessr sign-in window and wait for a `_ncfa` cookie to appear.
	 *  Returns the signed-in nickname.
	 */
	geoguessrLogin: () => __TAURI_INVOKE<string>("geoguessr_login"),
	/**  The signed-in user, or `None` when there is no session (or it was rejected). */
	geoguessrMe: () => __TAURI_INVOKE<GgUser | null>("geoguessr_me"),
	geoguessrLogout: () => __TAURI_INVOKE<null>("geoguessr_logout"),
	/**  Local-only check: is a token stored? Says nothing about its validity. */
	geoguessrHasSession: () => __TAURI_INVOKE<boolean>("geoguessr_has_session"),
	/**
	 *  Commit the map's uncommitted changes and return the new commit id.
	 *  `message` None auto-generates a `+a -r ~m` summary.
	 */
	storeCommit: (mapId: string, message: string | null) => __TAURI_INVOKE<string>("store_commit", { mapId, message }),
	/**  List all commits for a map, newest first. */
	storeListCommits: (mapId: string) => __TAURI_INVOKE<CommitInfo[]>("store_list_commits", { mapId }),
	/**
	 *  Restore a map to the state captured by a previous commit. The caller must reopen
	 *  the map afterwards (undo/redo is cleared).
	 */
	storeCheckoutCommit: (mapId: string, commitId: string) => __TAURI_INVOKE<null>("store_checkout_commit", { mapId, commitId }),
	/**  Read a single commit's delta (created/removed locations) for the diff viewer. */
	storeGetCommitDelta: (mapId: string, commitId: string) => __TAURI_INVOKE<CommitDelta>("store_get_commit_delta", { mapId, commitId }).then((v) => (({...v,created:v.created.map(i=>i),removed:v.removed.map(i=>i)}) as typeof v)),
	/**
	 *  Generate locations from a Vali map definition (JSON/JSONC text). Missing country
	 *  data is auto-downloaded like the Vali CLI. Returns the generated locations.
	 */
	valiGenerate: (definition: string) => __TAURI_INVOKE<ValiLocation[]>("vali_generate", { definition }).then((v) => (v.map(i=>({...i,zoom:i.zoom==null?i.zoom:i.zoom,pitch:i.pitch==null?i.pitch:i.pitch})) as typeof v)),
	/**  Download Vali coverage data. `country` = code/continent alias/None for all. */
	valiDownload: (country: string | null, full: boolean, updates: boolean) => __TAURI_INVOKE<null>("vali_download", { country, full, updates }),
	/**  Cancel an in-flight vali generate or download. */
	valiCancel: () => __TAURI_INVOKE<void>("vali_cancel"),
	/**  Subdivision weights for a country (JSON text, same shape as `vali subdivisions`). */
	valiSubdivisions: (country: string) => __TAURI_INVOKE<string>("vali_subdivisions", { country }),
};

/* Types */
/**
 *  A swap-removal from a render cell. JS must move the last element into `cell_index`
 *  and pop the array to mirror the Rust-side swap-remove.
 */
export type CellRemoval = {
	cell: string,
	cellIndex: number,
	id: number,
};

/**
 *  Override the RGBA color of a single marker within a cell (used when selection
 *  membership changes without a position change).
 */
export type ColorPatchEntry = {
	cell: string,
	cellIndex: number,
	r: number,
	g: number,
	b: number,
	a: number,
};

/**
 *  A commit's delta, returned to the frontend for the per-commit diff viewer.
 *  An updated location appears in both `created` (new) and `removed` (old).
 */
export type CommitDelta = {
	created: Location[],
	removed: Location[],
};

export type CommitDiff = {
	added: number,
	removed: number,
	modified: number,
};

export type CommitInfo = {
	id: string,
	mapId: string,
	parentId: string | null,
	message: string | null,
	treeHash: string | null,
	locationCount: number,
	createdAt: string,
} & CommitDiff;

/**
 *  How a field's values are compared when measuring how strongly it separates
 *  groups (selection disambiguation). The only un-inferrable property a field can
 *  declare is circularity (heading/azimuth=360, hour-of-day=24, month=12);
 *  everything else is inferred from `ExtraFieldType`.
 */
export type ComparisonType = { type: "linear" } | { type: "circular"; period: number } | { type: "categorical" };

export type Conflict = {
	key: string,
	kind: ConflictKind,
	/**  Base value is not persisted (only its hash), so conflicts surface local vs remote. */
	local: NormalizedSyncLocation | null,
	remote: NormalizedSyncLocation | null,
};

export type ConflictKind = 
/**  Both sides modified the same location differently. */
"update-update" | 
/**  One side deleted while the other modified. */
"delete-update" | 
/**  Both sides added the same identity with different content (hash collision only). */
"add-add";

/**  Result of a cross-map location copy. `target_name` feeds the toast. */
export type CopyToMapResult = {
	copied: number,
	skipped: number,
	targetName: string,
};

/**  The active and default data-folder paths, plus whether a custom override is in effect. */
export type DataLocation = {
	/**  Folder currently in use this session (default or override). */
	path: string,
	/**  OS default, ignoring any override -- used for the "reset" affordance. */
	default_path: string,
	/**  True when `path` differs from the OS default. */
	is_custom: boolean,
};

/**  A calendar component to group dates by. */
export type DatePart = "year" | "yearMonth" | "day" | "monthOfYear" | "hourOfDay";

/**  Aggregate database statistics for the debug panel. */
export type DbStats = {
	maps: number,
	locations: number,
	tags: number,
	commits: number,
	dbSizeBytes: number,
	journalMode: string,
	foreignKeys: boolean,
};

/**  Row count for a single SQLite table, used in the debug diagnostics panel. */
export type DbTableInfo = {
	name: string,
	rows: number,
};

/**
 *  Preview data for importing a file into the currently open map.
 *  Unlike bulk import, this shows per-field counts so the user can
 *  selectively drop fields (heading, panoId, etc.) before importing.
 */
export type EditorImportPreview = {
	locationCount: number,
	tags: Tag[],
	fields: FieldCount[],
	warnings: string[],
	/**  Temp-file path to preview positions: interleaved LE f32 `[lng, lat]` pairs. */
	previewPositionsPath: string,
	/**  `[west, south, east, north]` bounding box of the import, for map auto-focus. */
	bounds: [number, number, number, number] | null,
	/**
	 *  True when this import exceeds `IMPORT_AUTOCOMMIT_THRESHOLD` and will be
	 *  committed automatically (not undoable). Drives the import warning modal.
	 */
	willAutoCommit: boolean,
};

/**
 *  Combined result of an editor import: the mutation delta (for render pipeline)
 *  plus import-specific metadata.
 */
export type EditorImportResult = {
	importedCount: number,
	warnings: string[],
	/**  True when the import was large enough to autocommit; the caller commits it. */
	autoCommit: boolean,
	/**  Settings carried by the import (`extra.settings`) */
	settings: { [key in string]: any },
} & MutationResult;

/**
 *  Configuration for JSON export. Controls which fields are included and
 *  whether the export covers all locations or a specific selection.
 */
export type ExportOpts = {
	exportZoom: boolean,
	exportUnpanned: boolean,
	exportExtras: boolean,
	/**  When `Some`, restricts export to these location IDs (e.g. current selection). */
	scope: number[] | null,
	mapName: string,
	/**
	 *  Serialized `{id: {name, color}}` tag definitions from the store, used to
	 *  convert numeric tag IDs back to human-readable names in the output.
	 */
	tagsJson: string,
	extraFieldsJson: string | null,
};

/**
 *  Schema definition for a single `Location.extra` field. Stored in the map's
 *  `extra.fields` JSON. For enum types, `values` lists valid options and `labels`
 *  provides display names.
 */
export type ExtraFieldDef = {
	type: ExtraFieldType,
	label?: string | null,
	values?: string[] | null,
	labels?: { [key in string]: string } | null,
	/**
	 *  Optional override for how this field is compared during disambiguation.
	 *  `None` => inferred from `field_type` on the analysis side.
	 */
	comparison?: ComparisonType | null,
};

/**
 *  Type discriminant for `Location.extra` field definitions.
 *  Determines how the field is displayed and filtered in the UI.
 */
export type ExtraFieldType = "string" | "number" | "date" | "month" | "enum" | "array";

/**
 *  Field presence count for the editor import preview dialog, letting
 *  the user see which optional fields exist and decide which to keep/drop.
 */
export type FieldCount = {
	key: string,
	count: number,
};

/**
 *  Filter comparison operator. Single source of truth: specta renders the literal
 *  union, so the TS `FilterOp` type and `OP_LABELS` derive from this enum.
 */
export type FilterOp = "eq" | "neq" | "gt" | "lt" | "gte" | "lte" | "between" | "between_anyyear" | "between_anytime" | "has" | "nothas" | "contains" | "notcontains";

/**
 *  First-sync seeding when both sides already have pins. Only meaningful on the first sync
 *  (empty mapping); afterwards it's plain three-way. `Merge` never deletes.
 */
export type FirstSyncMode = "merge" | "mirrorFromRemote" | "mirrorFromLocal";

/**  Reverse geocode result: nearest populated place to a coordinate. */
export type GeoResult = {
	city: string,
	/**  First-level administrative division (state, province, region). */
	admin: string,
	country: string,
	/**  ISO 3166-1 alpha-2 (e.g. "US", "FR"). */
	country_code: string,
};

/**  The signed-in GeoGuessr account. */
export type GgUser = {
	id: string,
	nick: string,
	/**  Avatar pin path (e.g. `pin/<hash>.png`), served under `/images/` on geoguessr.com. */
	pin: string | null,
};

/**
 *  Summary of a single map found during bulk import preview.
 *  Shown in the import dialog so the user can select which maps to import.
 */
export type ImportPreviewEntry = {
	name: string,
	folder: string | null,
	locationCount: number,
	tagCount: number,
	warnings: string[],
};

/**  Result returned per map after a successful bulk import. */
export type ImportedMapInfo = {
	id: string,
	name: string,
	locationCount: number,
	tagCount: number,
};

/**  How a field value becomes a group key. Wire-mirrors the JS `KeySpec`. */
export type KeySpec = 
/**  String value of the field (enum/string/month "YYYY-MM"/number). */
{ kind: "value" } | 
/**  Equal-width numeric bins. */
{ kind: "numericBin"; binning: NumericBinning } | 
/**  Calendar component of a date (epoch seconds) or month ("YYYY-MM") field. */
{ kind: "datePart"; part: DatePart; tzLocal: boolean };

/**
 *  A single Street View location on a map.
 * 
 *  This is the atomic unit of data in the system. Locations are stored columnar
 *  in Arrow IPC on disk and addressed by `id` everywhere. The `id` is unique
 *  within a map and assigned by the store's monotonic allocator.
 */
export type Location = {
	/**
	 *  Monotonically increasing within a map. Zero is a sentinel meaning
	 *  "not yet assigned" (used during import before IDs are allocated).
	 */
	id: number,
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	panoId: string | null,
	/**  See [`LocationFlags`]. */
	flags: number,
	/**  Tag IDs applied to this location. References `Tag.id`. */
	tags: number[],
	/**  Arbitrary key-value metadata */
	extra: any | null,
	/**  Unix timestamp (seconds) */
	createdAt: number,
	modifiedAt: number | null,
};

/**
 *  Partial location update from JS. `None` fields are unchanged; `Some(None)` on
 *  nullable fields (panoId, extra, modifiedAt) explicitly sets the field to null.
 *  `extra` is a JSON Merge Patch (RFC 7386): keys shallow-merge, null values delete.
 */

/**
 *  Partial location update from JS. `None` fields are unchanged; `Some(None)` on
 *  nullable fields (panoId, extra, modifiedAt) explicitly sets the field to null.
 *  `extra` is a JSON Merge Patch (RFC 7386): keys shallow-merge, null values delete.
 */
export type LocationPatch_Deserialize = {
	lat?: number | null,
	lng?: number | null,
	heading?: number | null,
	pitch?: number | null,
	zoom?: number | null,
	panoId?: string | null,
	flags?: number | null,
	tags?: number[] | null,
	extra?: any | null,
	createdAt?: number | null,
	modifiedAt?: number | null,
};

/**
 *  Partial location update from JS. `None` fields are unchanged; `Some(None)` on
 *  nullable fields (panoId, extra, modifiedAt) explicitly sets the field to null.
 *  `extra` is a JSON Merge Patch (RFC 7386): keys shallow-merge, null values delete.
 */
export type LocationPatch = {
	lat: number | null,
	lng: number | null,
	heading: number | null,
	pitch: number | null,
	zoom: number | null,
	panoId: string | null,
	flags: number | null,
	tags: number[] | null,
	extra: any | null,
	createdAt: number | null,
	modifiedAt: number | null,
};

export type MapData = {
	meta: MapMeta,
};

/**
 *  Top-level `extra` JSON blob on a map row. Currently only holds field definitions,
 *  but structured as an object to allow future extensions.
 */
export type MapExtra = {
	fields?: { [key in string]: ExtraFieldDef } | null,
};

/**
 *  Action performed by a per-map key binding on the active location.
 *  New action kinds (e.g. copy-to-map) are added as variants here.
 */
export type MapKeyAction = { type: "applyTag"; tagId: number } | { type: "copyToMap"; mapId: string };

/**
 *  One user-defined per-map key binding. `key` is a combo string in the same
 *  canonical format as global hotkey bindings (e.g. "m", "Mod+Shift+x").
 */
export type MapKeyBinding = {
	key: string,
	action: MapKeyAction,
};

/**
 *  Full metadata for a map, deserialized from the SQLite `maps` row.
 *  JSON columns (settings, tags, extra, etc.) are parsed into typed structs.
 */
export type MapMeta = {
	id: string,
	name: string,
	description: string,
	folder: string | null,
	settings: MapSettings,
	scoreBounds: ScoreBounds,
	extra: MapExtra,
	tags: { [key in string]: Tag },
	labels: string[],
	locationCount: number,
	createdAt: string,
	updatedAt: string,
	lastOpenedAt: string | null,
};

/**
 *  Partial update for map metadata. Only non-`None` fields are written.
 *  `folder: Some(None)` explicitly unsets the folder (moves to root).
 */

/**
 *  Partial update for map metadata. Only non-`None` fields are written.
 *  `folder: Some(None)` explicitly unsets the folder (moves to root).
 */
export type MapMetaPatch_Deserialize = {
	name?: string | null,
	description?: string | null,
	folder?: string | null,
	settings?: MapSettings | null,
	scoreBounds?: ScoreBounds | null,
	extra?: MapExtra | null,
	tags?: { [key in string]: Tag } | null,
	labels?: string[] | null,
};

/**
 *  Partial update for map metadata. Only non-`None` fields are written.
 *  `folder: Some(None)` explicitly unsets the folder (moves to root).
 */
export type MapMetaPatch = {
	name: string | null,
	description: string | null,
	folder: string | null,
	settings: MapSettings | null,
	scoreBounds: ScoreBounds | null,
	extra: MapExtra | null,
	tags: { [key in string]: Tag } | null,
	labels: string[] | null,
};

/**
 *  Per-map editor preferences. Controls Street View lookup behavior (official vs
 *  unofficial, camera type filters), export defaults, and metadata enrichment.
 */
export type MapSettings = {
	pointAlongRoad?: boolean,
	preferDirection?: string | null,
	preferOfficial?: boolean,
	preferHigherQuality?: boolean,
	onlyOfficial?: boolean,
	cameraTypes?: string[] | null,
	defaultPanoId?: boolean,
	exportZoom?: boolean,
	exportUnpanned?: boolean,
	exportExtras?: boolean,
	searchRadius?: number | null,
	enrichMetadata?: boolean,
	enrichFields?: string[] | null,
	keyBindings?: MapKeyBinding[],
	/**  Virtual tag-tree nodes keyed by full slash path. Tree-view only. */
	virtualTags?: { [key in string]: VirtualTag },
	/**
	 *  Tag aliases: a second tree location (full slash path) -> the real tag id shown
	 *  there. Tree-view only; clicking the alias leaf toggles the real tag.
	 */
	aliases?: { [key in string]: number },
};

/**
 *  Unified response for every mutation IPC. Bundles the store status, render delta,
 *  optional selection sync, optional newly-discovered extra-field keys, and optional
 *  updated tags. JS applies all of these atomically to stay in sync with the Rust state.
 *  `new_field_defs` carries the inferred/known field definitions for extra-field keys
 *  discovered for the first time in this mutation. JS merges them straight into the
 *  field-def registry, so field metadata is live without a reload.
 */
export type MutationResult = {
	delta: RenderDelta,
	selectionSync: SelectionSync | null,
	newFieldDefs: { [key in string]: ExtraFieldDef } | null,
	tags: { [key in number]: Tag } | null,
} & StoreStatus;

/**
 *  The syncable contract: the only fields that participate in diffing. Everything else is
 *  owned by exactly one side and would register as a phantom change.
 */
export type NormalizedSyncLocation = {
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	panoId: string | null,
	/**  Remote-meaningful bits only; virtual bits are stripped. */
	flags: number,
	/**  Tag names, deduped and sorted. Empty for providers with no tag support. */
	tags: string[],
};

/**  Equal-width bin sizing. `count` derives the width from the data range; `width` fixes it. */
export type NumericBinning = { by: "count"; n: number } | { by: "width"; w: number };

/**
 *  One partition group: a stable key, the ids it holds, and (numeric bins only) the
 *  `[lo, hi]` bounds so JS can rebuild a live Filter for whole-map gradients.
 */
export type PartitionBucket = {
	key: string,
	ids: number[],
	bin: [number, number] | null,
};

/**  Metadata for a user-installed plugin, read from `plugins/{id}/manifest.json`. */

/**  Metadata for a user-installed plugin, read from `plugins/{id}/manifest.json`. */
export type PluginManifest_Deserialize = {
	id: string,
	name: string,
	description: string,
	icon: string,
	main: string,
	version: string,
	sidecar: PluginSidecar_Deserialize | null,
};

/**  Metadata for a user-installed plugin, read from `plugins/{id}/manifest.json`. */
export type PluginManifest = {
	id: string,
	name: string,
	description: string,
	icon: string,
	main: string,
	version: string,
	sidecar?: PluginSidecar | null,
};

/**  A plugin's declared sidecar binary (downloaded from GitHub Releases on install). */

/**  A plugin's declared sidecar binary (downloaded from GitHub Releases on install). */
export type PluginSidecar_Deserialize = {
	name: string,
	version: string,
	/**  Expected SHA-256 hex digest of the platform-specific zip archive. */
	sha256: string | null,
};

/**  A plugin's declared sidecar binary (downloaded from GitHub Releases on install). */
export type PluginSidecar = {
	name: string,
	version: string,
	/**  Expected SHA-256 hex digest of the platform-specific zip archive. */
	sha256?: string | null,
};

/**
 *  GeoJSON-like polygon geometry. `coordinates` is the primary polygon (outer ring +
 *  optional holes). `extra_polygons` allows multipolygon selections (e.g., from GeoJSON import).
 */
export type PolygonGeometry = {
	coordinates: (([number, number])[])[],
	extraPolygons?: ((([number, number])[])[])[] | null,
	properties?: any | null,
};

export type PresenceActivity = {
	details: string | null,
	state: string | null,
	largeImage: string | null,
	largeText: string | null,
	smallImage: string | null,
	smallText: string | null,
	/**  Unix seconds; Discord renders an "elapsed" timer counting up from here. */
	start: number | null,
};

/**
 *  A remote-originated create for JS to apply. `remote_id` is the handle its mapping row must
 *  carry once created (a positional push reindexes to its desired-document position).
 */
export type PullCreate = {
	fields: NormalizedSyncLocation,
	remoteId: number,
	hash: string,
};

/**  A remote-originated update for JS to apply to an existing local id. */
export type PullUpdate = {
	localId: number,
	patch: SyncPatch,
};

/**  One mapping row. `hash` is the plugin's content fingerprint (opaque text to us). */
export type RemoteMappingRow = {
	localId: number,
	/**  Remote ids can exceed u32 (observed ~1.2e10), so i64. */
	remoteId: number,
	hash: string,
};

/**
 *  Incremental render update sent to JS after a mutation. Contains adds, position/heading
 *  patches, swap-removals, and color patches (for selection overlay changes).
 *  `full_reset` signals JS to discard all cell data and re-fetch via `store_fill_render_file`.
 */
export type RenderDelta = {
	added: RenderEntry[],
	updated: RenderPatchEntry[],
	removed: CellRemoval[],
	colorPatches: ColorPatchEntry[],
	fullReset: boolean,
};

/**  A newly-added marker to a render cell: position, heading, and base color. */
export type RenderEntry = {
	cell: string,
	id: number,
	lng: number,
	lat: number,
	heading: number,
	r: number,
	g: number,
	b: number,
	a: number,
};

/**  Partial update to an existing marker within its cell (position and/or heading changed). */
export type RenderPatchEntry = {
	cell: string,
	cellIndex: number,
	lng: number | null,
	lat: number | null,
	heading: number | null,
};

/**
 *  Parameters for a full render rebuild. `marker_style` ("arrow" or "pin") determines
 *  whether heading angles are written. The bounding box fields are currently unused
 *  (no viewport culling -- all locations are rendered).
 */
export type RenderRequest = {
	west?: number,
	south?: number,
	east?: number,
	north?: number,
	selectedIds?: number[] | null,
	markerStyle?: string,
	markerColor?: [number, number, number] | null,
};

/**  Which side won a resolved conflict; serialized as "local"/"remote". */
export type ResolutionSide = "local" | "remote";

/**
 *  Inbound payload for creating a session. `order` is the frozen worklist (must be non-empty);
 *  the cursor starts at its first id and `reviewed` starts empty.
 */
export type ReviewCreate = {
	mapId: string,
	name: string,
	sourceKey: string,
	sourceProps: any,
	order: number[],
};

/**
 *  A review session as returned to the frontend. `order`/`reviewed` are decoded from the
 *  JSON-text columns; `source_props` is the originating `SelectionProps` (opaque here).
 */
export type ReviewSession = {
	id: string,
	mapId: string,
	name: string,
	sourceKey: string,
	sourceProps: any,
	order: number[],
	reviewed: number[],
	cursorId: number,
	status: string,
	createdAt: string,
	updatedAt: string,
};

/**
 *  Partial update. Any `Some` field is written; `None` leaves the column untouched.
 *  `ordering`/`reviewed` carry the full replacement arrays (used by reconciliation pruning).
 */
export type ReviewUpdate = {
	id: string,
	name?: string | null,
	cursorId: number | null,
	reviewed: number[] | null,
	ordering: number[] | null,
	status: string | null,
};

/**  Result of `store_save_dirty`: bytes written to the delta sidecar (0 = skipped). */
export type SaveResult = {
	savedBytes: number,
};

/**
 *  Which locations to operate on: the whole map or the current selection. Resolved in Rust
 *  against the maintained selection set.
 */
export type Scope = { kind: "all" } | { kind: "selected" };

/**
 *  Score bounding box: either `"auto"` (computed from locations) or an
 *  explicit `[south, west, north, east]` rectangle.
 */
export type ScoreBounds = string | [number, number, number, number];

/**  A panorama visit record as returned to the frontend. */
export type SeenEntry = {
	id: number,
	panoId: string,
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	enteredAt: number,
	mapId: string | null,
	locationId: number | null,
	countryCode: string | null,
	address: string | null,
	thumbnail: string | null,
};

/**
 *  Optional filters for seen-history queries. All fields are AND-combined.
 *  `search` does a substring match on the `address` column.
 */
export type SeenFilter = {
	country?: string | null,
	mapId?: string | null,
	search?: string | null,
};

/**
 *  Map id + display name pair for the "filter by map" dropdown.
 *  Name is resolved from the `maps` table when available, falling back to raw id.
 */
export type SeenMapInfo = {
	id: string,
	name: string,
};

/**
 *  Inbound payload for recording a new panorama visit. Same shape as `SeenEntry`
 *  minus the auto-assigned `id`.
 */
export type SeenWriteEntry = {
	panoId: string,
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	enteredAt: number,
	mapId: string | null,
	locationId: number | null,
	countryCode: string | null,
	address: string | null,
	thumbnail: string | null,
};

/**
 *  A named, colored selection. `key` is deterministic (e.g., `"tag:5"`, `"polygon:abc"`)
 *  so JS can diff selections across syncs. `color` is the RGB overlay color.
 */
export type Selection = {
	key: string,
	color: [number, number, number],
	props: SelectionProps,
};

/**  Input for `store_sync_selections`: selection criteria + display color. */
export type SelectionInput = {
	/**  Deterministic selection key (e.g. `"tag:5"`), used to return per-node counts back keyed. */
	key: string,
	props: SelectionProps,
	color: [number, number, number],
	/**  Counted, but kept out of the overlay and the selected set. */
	ghosted?: boolean,
};

/**
 *  Discriminated union of all selection types. Serialized with `{ "type": "..." }` tag
 *  for JS interop. Simple types (Tag, Untagged, PanoIds, etc.) resolve in O(N) with
 *   parallel batch scans. Composites (Intersection, Union, Invert) recursively resolve
 *  children. Duplicates uses a grid-accelerated spatial scan.
 */
export type SelectionProps = { type: "Locations"; locations: number[]; name: string | null } | { type: "Everything" } | { type: "Polygon"; polygon: PolygonGeometry; includeInformational: boolean } | { type: "Tag"; tagId: number } | { type: "Untagged" } | { type: "Unpanned" } | { type: "PanoIds" } | { type: "NotPanoIds" } | { type: "Uncommitted" } | { type: "Manual"; locations: number[] } | { type: "Duplicates"; distance: number } | { type: "ValidationState"; locations: number[]; state: number } | { type: "Reviewed"; locations: number[]; sessionId: string; mode: string } | { type: "Intersection"; selections: Selection[] } | { type: "Union"; selections: Selection[] } | { type: "Invert"; selections: Selection[] } | { type: "Filter"; field: string; op: FilterOp; value: any; value2?: any | null; tzLocal?: boolean } | { type: "TopK"; field: string; k: number; ascending: boolean };

/**
 *  Selection bitmask sync payload. `bitmask` carries the packed per-cell bitmask bytes
 *  inline in the IPC response (no shared temp file → no clobber race under concurrent
 *  mutations). `None` when nothing changed. `counts` gives per-selection match counts.
 */
export type SelectionSync = {
	/**  Resolved count per selection node, keyed by `Selection.key` (top-level and nested). */
	counts: { [key in string]: number },
	bitmask: number[] | null,
	selectedCount: number,
};

export type SideCounts = {
	create: number,
	update: number,
	delete: number,
};

export type SpacedPickResult = {
	ids: number[],
	distanceM: number,
};

/**
 *  Metadata snapshot returned to JS after every mutation. JS uses `version` to
 *  detect stale responses and `canUndo`/`canRedo` for toolbar button state.
 *  `known_field_keys` lists every extra-field key that exists in location data
 *  on this map. Add-only within a session; seeded from `MapMeta.extra.fields`
 *  on map open.
 */
export type StoreStatus = {
	version: number,
	locationCount: number,
	canUndo: boolean,
	canRedo: boolean,
	/**
	 *  `None` when the mutation did not change any tag count (`finish_mutation`
	 *  strips it), so JS keeps its reference and consumers skip re-rendering.
	 */
	tagCounts: { [key in number]: number } | null,
	knownFieldKeys: string[],
};

/**  Lightweight status for polling: count, version, and whether unsaved changes exist. */
export type SummaryResult = {
	locationCount: number,
	version: number,
	dirtyCount: number,
};

/**
 *  Only the fields a pull genuinely changes. A field the provider cannot represent reads as empty
 *  on the remote side and must not overwrite local data, so absent fields are left untouched.
 *  `pano_id` applies only when `pano_id_set` is true (a cleared panoId is a real change to `null`).
 */
export type SyncPatch = {
	lat: number | null,
	lng: number | null,
	heading: number | null,
	pitch: number | null,
	zoom: number | null,
	panoIdSet: boolean,
	panoId: string | null,
	flags: number | null,
	tags: string[] | null,
};

/**  Everything the reconcile settled to, for the JS side. Every array is empty on an unchanged map. */
export type SyncReconcileResult = {
	/**  Remote-applied counts; mirror-from-local deletes fold into `delete`. */
	pushed: SideCounts,
	/**  Local-applied counts; mirror-from-remote deletes fold into `delete`. */
	pulled: SideCounts,
	adopted: number,
	conflicts: Conflict[],
	neededTags: string[],
	pullCreates: PullCreate[],
	pullUpdates: PullUpdate[],
	pullDeleteIds: number[],
	mirrorLocalDeleteIds: number[],
};

/**
 *  A user-defined label that can be applied to any number of locations.
 * 
 *  Tags are stored in `MapMeta` and referenced by id in each `Location.tags`.
 *  The `count` field is maintained by callers during batch mutations, not by
 *  the overlay add/remove methods.
 */
export type Tag = {
	id: number,
	name: string,
	/**
	 *  Hex color string (e.g. "#3a7fc2"). Generated deterministically from
	 *  the tag name via `util::color_for_name` when not explicitly set.
	 */
	color: string,
	visible?: boolean,
	/**
	 *  Display order in the sidebar tag list. `None` for legacy tags
	 *  that predate ordered insertion.
	 */
	order?: number | null,
	/**
	 *  Number of locations currently carrying this tag. Denormalized for
	 *  fast sidebar display -- kept in sync by callers after batch edits.
	 */
	count?: number,
	/**
	 *  Document links from the map JSON's `extra.tags[name].doclinks` --
	 *  URLs into external docs (e.g. Google Docs heading links). Read-only
	 *  in the app; round-trips through import/export.
	 */
	doclinks?: string[],
};

/**  Patchable fields of a `Tag`. Subset by design: id/count/visible aren't editable here. */
export type TagPatch = {
	name?: string | null,
	color?: string | null,
	/**  Full replacement for the tag's doclink URLs (empty vec clears). */
	doclinks?: string[] | null,
};

/**
 *  Generic `{id, patch}` update envelope, parameterized by the patch type. Specta
 *  has no `Partial<T>`, and a patch is a deliberate *subset* of patchable fields, so
 *  each entity names its own patch struct (e.g. `TagPatch`) rather than deriving one.
 */
export type Update<P> = {
	id: number,
	patch: P,
};


export type ValiLocation_Deserialize = {
	lat: number,
	lng: number,
	heading: number,
	zoom: number | null,
	pitch: number | null,
	panoId: string | null,
	tags: string[],
};

export type ValiLocation = {
	lat: number,
	lng: number,
	heading: number,
	zoom?: number | null,
	pitch?: number | null,
	panoId?: string | null,
	tags: string[],
};

/**
 *  Per-map config for a virtual tag-tree node — a folder node with no underlying
 *  tag (e.g. "a" when only "a/b" and "a/c" exist). Keyed by the node's full slash
 *  path in `MapSettings::virtual_tags`. Tree-view only; never creates a real tag.
 */
export type VirtualTag = {
	color?: string | null,
};

