// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Milliseconds from `run()` to the frontend's first call; logged once. */
	appReady: () => __TAURI_INVOKE<number>("app_ready"),
	/**
	 *  Write text to a temp file and return its path. `name` is a leaf filename
	 *  (cannot contain path separators).
	 */
	writeTempFile: (name: string, content: string) => __TAURI_INVOKE<string>("write_temp_file", { name, content }),
	/**  Read a file as UTF-8 text (temp files, plugin sources). */
	readFile: (path: string) => __TAURI_INVOKE<string>("read_file", { path }),
	/**  Return the app's data directory path. */
	getAppDataDir: () => __TAURI_INVOKE<string>("get_app_data_dir"),
	/**  Return the current and default data-folder paths, and whether a custom override is active. */
	getDataLocation: () => __TAURI_INVOKE<DataLocation>("get_data_location"),
	/**
	 *  Set or clear the data-folder override. Takes effect after relaunch and does not
	 *  move existing data.
	 */
	setDataLocation: (path: string | null) => __TAURI_INVOKE<null>("set_data_location", { path }),
	/**  Open the app's data folder in the OS file explorer. */
	openDataFolder: () => __TAURI_INVOKE<null>("open_data_folder"),
	/**  Open the app's log file in the OS default handler. */
	openLogFile: () => __TAURI_INVOKE<null>("open_log_file"),
	/**
	 *  First caller per app run wins the silent update pass. Every webview boots the
	 *  plugin loader, so without this a restored editor window plus the map list run
	 *  two full passes -- double registry fetches, double downloads, and interleaved
	 *  install progress for the same plugin.
	 */
	claimPluginUpdatePass: () => __TAURI_INVOKE<boolean>("claim_plugin_update_pass"),
	/**  Manifests of every installed plugin. */
	listUserPlugins: () => __TAURI_INVOKE<PluginManifest[]>("list_user_plugins"),
	/**
	 *  Install a plugin from the marketplace repo: its `manifest.json`, the main JS file, and
	 *  the procedure module it declares. `git_ref` pins an older build; `None` takes master.
	 */
	installPlugin: (id: string, gitRef: string | null) => __TAURI_INVOKE<PluginManifest>("install_plugin", { id, gitRef }),
	/**  Delete a plugin's directory. */
	uninstallPlugin: (id: string) => __TAURI_INVOKE<null>("uninstall_plugin", { id }),
	/**
	 *  Download a plugin's sidecar bundle from GitHub Releases and extract it under
	 *  `{appData}/plugins/{plugin_id}/sidecar/`. Emits `sidecar-install-progress`.
	 */
	sidecarInstall: (pluginId: string, name: string, version: string) => __TAURI_INVOKE<null>("sidecar_install", { pluginId, name, version }),
	/**  Installed sidecar version for a plugin, or `None` if not installed. */
	sidecarInstalledVersion: (pluginId: string) => __TAURI_INVOKE<string | null>("sidecar_installed_version", { pluginId }),
	/**
	 *  Run one unit of work on a plugin's sidecar. Commands the manifest lists under
	 *  `serve` go to the plugin's resident process; the rest get a one-shot child.
	 *  Streams `sidecar-line` (one JSON object per unit) and `sidecar-log` (stderr),
	 *  then exactly one `sidecar-done`, all keyed by the returned request id.
	 */
	sidecarRequest: (pluginId: string, command: string, payload: string | null) => __TAURI_INVOKE<number>("sidecar_request", { pluginId, command, payload }),
	/**  Stop all sidecar processes for a plugin. */
	sidecarStop: (pluginId: string) => __TAURI_INVOKE<null>("sidecar_stop", { pluginId }),
	/**  Stop all sidecar processes across every plugin. */
	sidecarStopAll: () => __TAURI_INVOKE<null>("sidecar_stop_all"),
	/**  Cancel a running sidecar request. No-op if the request already finished. */
	sidecarCancel: (reqId: number) => __TAURI_INVOKE<null>("sidecar_cancel", { reqId }),
	/**  Whether the border dataset for `level` is available on disk. */
	checkBorderFile: (level: string) => __TAURI_INVOKE<boolean>("check_border_file", { level }),
	/**  Download the border dataset for `level` from the repository. */
	downloadBorderFile: (level: string) => __TAURI_INVOKE<null>("download_border_file", { level }),
	/**
	 *  Return the border polygon containing (`lat`, `lng`) at the given detail
	 *  `level`, or `None` if the point falls outside every feature.
	 */
	borderLookup: (lat: number, lng: number, level: string) => __TAURI_INVOKE<PolygonGeometry | null>("border_lookup", { lat, lng, level }).then((v) => (v==null?v:({...v,coordinates:v.coordinates.map(i=>i.map(i=>i.map(i=>i))),extraPolygons:v.extraPolygons==null?v.extraPolygons:v.extraPolygons.map(i=>i.map(i=>i.map(i=>i.map(i=>i))))}) as typeof v)),
	/**
	 *  Classify each `(lat, lng)` to the name of its containing border feature at
	 *  `level` (subdivision names for "adm1"). `None` for points outside every feature.
	 */
	borderClassify: (level: string, points: ([number, number])[]) => __TAURI_INVOKE<(string | null)[]>("border_classify", { level, points: points.map(i=>i) }),
	/**
	 *  Return the nearest city, administrative region, and country for a coordinate.
	 *  Always returns `Some` - the dataset covers every landmass.
	 */
	reverseGeocode: (lat: number, lng: number) => __TAURI_INVOKE<GeoResult | null>("reverse_geocode", { lat, lng }),
	/**  Set the Discord Rich Presence activity. No-op when Discord is not running. */
	discordPresenceSet: (activity: PresenceActivity) => __TAURI_INVOKE<null>("discord_presence_set", { activity }),
	/**  Clear the Discord Rich Presence activity. No-op when Discord is not running. */
	discordPresenceClear: () => __TAURI_INVOKE<null>("discord_presence_clear"),
	/**
	 *  Begin device-flow sign-in. Returns the code to show the user; call
	 *  [`github_poll_login`] afterwards to wait for them to finish authorizing.
	 */
	githubStartLogin: () => __TAURI_INVOKE<DeviceCodeInfo>("github_start_login"),
	/**
	 *  Wait for the user to authorize the code from [`github_start_login`].
	 *  Resolves with the signed-in account.
	 */
	githubPollLogin: () => __TAURI_INVOKE<GhUser>("github_poll_login"),
	/**  The signed-in user, or `None` when there is no session (or it was rejected). */
	githubMe: () => __TAURI_INVOKE<GhUser | null>("github_me"),
	/**  Sign out of GitHub and clear the stored session. */
	githubLogout: () => __TAURI_INVOKE<null>("github_logout"),
	/**  Local-only check: is a token stored? Says nothing about its validity. */
	githubHasSession: () => __TAURI_INVOKE<boolean>("github_has_session"),
	/**  File a bug report as the signed-in GitHub user. */
	githubCreateIssue: (title: string, body: string, labels: string[]) => __TAURI_INVOKE<IssueRef>("github_create_issue", { title, body, labels }),
	/**  Fetch a report's current state and comments as the signed-in GitHub user. */
	githubIssueThread: (number: number) => __TAURI_INVOKE<IssueThread>("github_issue_thread", { number }),
	/**  The tail of `mma.log`, scrubbed. Empty string when there is no log yet. */
	feedbackLogTail: () => __TAURI_INVOKE<string>("feedback_log_tail"),
	/**  Whether the anonymous tier is available in this build. */
	feedbackAnonymousAvailable: () => __TAURI_INVOKE<boolean>("feedback_anonymous_available"),
	/**
	 *  File a bug report anonymously (no account required). Returns a reference the
	 *  caller can use to check for replies via [`feedback_anonymous_thread`].
	 */
	feedbackSubmitAnonymous: (title: string, body: string, installId: string) => __TAURI_INVOKE<AnonIssueRef>("feedback_submit_anonymous", { title, body, installId }),
	/**  Upload an image attachment for a bug report and return its URL. */
	feedbackUploadAttachment: (path: string, name: string) => __TAURI_INVOKE<AttachmentRef>("feedback_upload_attachment", { path, name }),
	/**
	 *  Request that standard labels be applied to a report the user filed. Best-effort:
	 *  a failure here does not affect the report itself.
	 */
	feedbackRequestLabel: (number: number) => __TAURI_INVOKE<null>("feedback_request_label", { number }),
	/**  Fetch the current state and replies for an anonymous report. */
	feedbackAnonymousThread: (number: number, token: string) => __TAURI_INVOKE<IssueThread>("feedback_anonymous_thread", { number, token }),
	/**
	 *  Check for an update at `endpoint` (a release's `latest.json`). Returns `None`
	 *  when the announced version is not newer than the running one.
	 */
	updateCheck: (endpoint: string) => __TAURI_INVOKE<UpdateAvailable | null>("update_check", { endpoint }),
	/**
	 *  Download and install whatever the last [`update_check`] found. The installer replaces the
	 *  running app, so nothing after this is guaranteed to run -- the caller saves its state first.
	 */
	updateInstall: () => __TAURI_INVOKE<null>("update_install"),
	/**
	 *  Start (or re-key) the remote API server. Idempotent: a running server just
	 *  picks up the new key. Returns the base URL.
	 */
	remoteApiStart: (key: string) => __TAURI_INVOKE<string>("remote_api_start", { key }),
	/**  Stop the remote API server. */
	remoteApiStop: () => __TAURI_INVOKE<null>("remote_api_stop"),
	/**  Deliver the result for remote API request `id`. `payload` is JSON text. */
	remoteApiRespond: (id: number, ok: boolean, payload: string) => __TAURI_INVOKE<void>("remote_api_respond", { id, ok, payload }),
	/**
	 *  Open a map and return its initial state (tag counts, undo/redo availability).
	 *  Must be called before any other store commands.
	 */
	storeOpenMap: (mapId: string) => __TAURI_INVOKE<StoreStatus>("store_open_map", { mapId }).then((v) => (({...v,values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Close the open map, saving unsaved changes first. */
	storeCloseMap: () => __TAURI_INVOKE<null>("store_close_map"),
	/**  Save uncommitted changes to disk. No-op when nothing has changed. */
	storeSaveDirty: () => __TAURI_INVOKE<SaveResult>("store_save_dirty"),
	/**  Copy locations already stored in this map into another map. */
	storeCopyLocationsToMap: (targetMapId: string, selector: Selector) => __TAURI_INVOKE<CopyToMapResult>("store_copy_locations_to_map", { targetMapId, selector }),
	/**
	 *  Add caller-supplied locations to another map. Tags are matched by name against this
	 *  map's tag table.
	 */
	storeAddLocationsToMap: (targetMapId: string, locations: Location[]) => __TAURI_INVOKE<CopyToMapResult>("store_add_locations_to_map", { targetMapId, locations: locations.map(i=>i) }),
	/**  Return the map's current location count, store version, and unsaved-change count. */
	storeGetSummary: () => __TAURI_INVOKE<SummaryResult>("store_get_summary"),
	/**  Add new locations, allocating sequential IDs. Undoable. */
	storeAddLocations: (locations: Location[]) => __TAURI_INVOKE<MutationResult>("store_add_locations", { locations: locations.map(i=>i) }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**
	 *  Add locations from a chunked upload session (see `store_upload_begin`).
	 *  Same behavior as `store_add_locations`: one atomic mutation, undoable.
	 */
	storeAddLocationsUploaded: (sessionDir: string) => __TAURI_INVOKE<MutationResult>("store_add_locations_uploaded", { sessionDir }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Remove locations by ID. Undoable. */
	storeRemoveLocations: (ids: number[]) => __TAURI_INVOKE<MutationResult>("store_remove_locations", { ids }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**
	 *  Apply partial patches to existing locations. `record_undo` defaults to true;
	 *  set to false for ephemeral updates (e.g., plugin-driven batch modifications
	 *  that manage their own undo).
	 */
	storeUpdateLocations: (updates: Update<LocationPatch_Deserialize>[], recordUndo: boolean | null) => __TAURI_INVOKE<MutationResult>("store_update_locations", { updates, recordUndo }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Set (or clear) the active location. */
	storeSetActive: (id: number | null) => __TAURI_INVOKE<null>("store_set_active", { id }),
	/**  Set the default marker color for new render updates. */
	storeSetMarkerColor: (color: [number, number, number]) => __TAURI_INVOKE<null>("store_set_marker_color", { color }),
	/**  Ids of every location the selector resolves to, ascending. */
	storeResolve: (selector: Selector) => __TAURI_INVOKE<number[]>("store_resolve", { selector }),
	/**  Count how many locations the selector matches. */
	storeCount: (selector: Selector) => __TAURI_INVOKE<number>("store_count", { selector }),
	/**  `n` ids drawn uniformly at random from the selected set, without replacement. */
	storeSample: (selector: Selector, n: number) => __TAURI_INVOKE<number[]>("store_sample", { selector, n }),
	/**
	 *  An evenly spaced subset: exactly one of `target_count` (thin to N, maximizing
	 *  spacing) or `min_distance_m` (keep as many as fit at that spacing).
	 */
	storeSpaced: (selector: Selector, targetCount: number | null, minDistanceM: number | null) => __TAURI_INVOKE<SpacedPickResult>("store_spaced", { selector, targetCount, minDistanceM }),
	/**  Group by a derived key, returning `{ key, ids, bin }` per group. */
	storeGroupBy: (selector: Selector, field: string, key: KeySpec) => __TAURI_INVOKE<PartitionBucket[]>("store_group_by", { selector, field, key }).then((v) => (v.map(i=>({...i,bin:i.bin==null?i.bin:i.bin.map(i=>i)})) as typeof v)),
	/**  Group locations by a derived key, returning counts only (no member ids). */
	storeCountBy: (selector: Selector, field: string, key: KeySpec) => __TAURI_INVOKE<([string, number])[]>("store_count_by", { selector, field, key }),
	/**  Distinct values of `field` across the selected set, sorted. */
	storeValues: (selector: Selector, field: string) => __TAURI_INVOKE<string[]>("store_values", { selector, field }),
	/**
	 *  How many rows hold a value for each field, key-sorted: `extra` keys and the built-in
	 *  columns a row can lack.
	 */
	storeCoverage: (selector: Selector) => __TAURI_INVOKE<([string, number])[]>("store_coverage", { selector }),
	/**  Read specific fields across matched locations, returned as one column per field. */
	storeColumns: (selector: Selector, fields: string[]) => __TAURI_INVOKE<Columns>("store_columns", { selector, fields }),
	/**  Bounding box `[west, south, east, north]`, or `None` when the set is empty. */
	storeBounds: (selector: Selector) => __TAURI_INVOKE<[number, number, number, number] | null>("store_bounds", { selector }).then((v) => (v==null?v:v.map(i=>i) as typeof v)),
	/**
	 *  Collect all matched locations as full rows. Prefer a projection (`store_columns`,
	 *  `store_values`) when only specific fields are needed.
	 */
	storeCollect: (selector: Selector) => __TAURI_INVOKE<Rows>("store_collect", { selector }),
	/**  Apply a field operation to every location matched by `selector`. */
	storeApplyFieldOp: (selector: Selector, op: FieldOp, recordUndo: boolean | null) => __TAURI_INVOKE<FieldOpResult>("store_apply_field_op", { selector, op, recordUndo }).then((v) => (({...v,mutation:({...v.mutation,delta:({...v.mutation.delta,added:v.mutation.delta.added.map(i=>i),updated:v.mutation.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.mutation.values,fieldDefs:v.mutation.values.fieldDefs==null?v.mutation.values.fieldDefs:Object.fromEntries(Object.entries(v.mutation.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})}) as typeof v)),
	/**  The parse error for `src`, or nothing when it parses. For the dialog's live check. */
	fieldExprError: (src: string) => __TAURI_INVOKE<string | null>("field_expr_error", { src }),
	/**
	 *  Count locations by country using offline point-in-polygon. Returns (ISO-A2, count) pairs.
	 *  `level` selects border precision, falling back to "light" if unavailable.
	 */
	storeCountryDistribution: (selector: Selector, level: string) => __TAURI_INVOKE<([string, number])[]>("store_country_distribution", { selector, level }),
	/**  Find all locations within `radius_m` metres of (`lat`, `lng`). */
	storeFindNearby: (lat: number, lng: number, radiusM: number) => __TAURI_INVOKE<Location[]>("store_find_nearby", { lat, lng, radiusM }).then((v) => (v.map(i=>i) as typeof v)),
	/**
	 *  For each input point, whether any existing location lies within `radius_m` metres.
	 *  Batch form for probing many coordinates at once.
	 */
	storeNearAny: (lats: number[], lngs: number[], radiusM: number) => __TAURI_INVOKE<boolean[]>("store_near_any", { lats: lats.map(i=>i), lngs: lngs.map(i=>i), radiusM }),
	/**
	 *  Create tags by name and assign them to the locations matched by `selector`.
	 *  Deduplicates case-insensitively: if a tag with the same name already exists, it is reused.
	 */
	storeCreateTags: (names: string[], selector: Selector) => __TAURI_INVOKE<MutationResult>("store_create_tags", { names, selector }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**
	 *  Rename and/or recolor tags in one batch. Renaming onto an existing name (case-insensitive)
	 *  merges the two tags.
	 */
	storeUpdateTags: (updates: Update<TagPatch>[]) => __TAURI_INVOKE<MutationResult>("store_update_tags", { updates }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Remove tags and strip them from all locations that carry them. Undoable. */
	storeDeleteTags: (tagIds: number[]) => __TAURI_INVOKE<MutationResult>("store_delete_tags", { tagIds }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Set the display order of tags. Each tag's position is its index in `ordered_ids`. */
	storeReorderTags: (orderedIds: number[]) => __TAURI_INVOKE<MutationResult>("store_reorder_tags", { orderedIds }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Undo the last edit. */
	storeUndo: () => __TAURI_INVOKE<MutationResult>("store_undo").then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Redo the last undone edit. */
	storeRedo: () => __TAURI_INVOKE<MutationResult>("store_redo").then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Clear both undo and redo stacks. */
	storeResetUndo: () => __TAURI_INVOKE<MutationResult>("store_reset_undo").then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Return the uncommitted change counts (added, removed, modified) since the last commit. */
	storeCommitDiff: () => __TAURI_INVOKE<[number, number, number]>("store_commit_diff"),
	/**
	 *  Replace all active selections and resolve them against current data. Returns
	 *  per-selection counts and a bitmask for the marker overlay.
	 */
	storeSyncSelections: (sels: SelectionInput[]) => __TAURI_INVOKE<SelectionSync>("store_sync_selections", { sels }),
	/**
	 *  Find groups of locations within `distance` metres of each other (transitive).
	 *  Returns groups of IDs, each with at least two members.
	 */
	storeDuplicateGroups: (distance: number) => __TAURI_INVOKE<number[][]>("store_duplicate_groups", { distance }),
	/**
	 *  Merge each duplicate group within `distance` metres into one location, unioning tags
	 *  and extra fields. `score` ranks which location survives; blank uses the default ranking.
	 *  Undoable.
	 */
	storeMergeDuplicates: (distance: number, score: string | null) => __TAURI_INVOKE<MutationResult>("store_merge_duplicates", { distance, score }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**
	 *  Remove duplicate locations within `distance` metres of each other, keeping the
	 *  best-scored survivor per cluster. Undoable.
	 */
	storePruneDuplicates: (selector: Selector, distance: number, score: string | null) => __TAURI_INVOKE<MutationResult>("store_prune_duplicates", { selector, distance, score }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Rebuild all marker render data from scratch and return the file path to fetch it from. */
	storeFillRenderFile: (req: RenderRequest) => __TAURI_INVOKE<string>("store_fill_render_file", { req }),
	/**  Resolve a marker pick (cell key + index within cell) to a location ID. */
	storeResolvePick: (cell: string, cellIndex: number) => __TAURI_INVOKE<number | null>("store_resolve_pick", { cell, cellIndex }),
	/**  Return metadata for every map in the database. */
	storeListMaps: () => __TAURI_INVOKE<MapMeta[]>("store_list_maps").then((v) => (v.map(i=>({...i,extra:({...i.extra,fields:i.extra.fields==null?i.extra.fields:Object.fromEntries(Object.entries(i.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})) as typeof v)),
	/**  Fetch a single map's metadata by ID. Returns `None` if not found. */
	storeGetMap: (id: string) => __TAURI_INVOKE<MapMeta | null>("store_get_map", { id }).then((v) => (v==null?v:({...v,extra:({...v.extra,fields:v.extra.fields==null?v.extra.fields:Object.fromEntries(Object.entries(v.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Create a new empty map with default settings. Returns the full metadata. */
	storeCreateMap: (name: string, folder: string | null) => __TAURI_INVOKE<MapMeta>("store_create_map", { name, folder }).then((v) => (({...v,extra:({...v.extra,fields:v.extra.fields==null?v.extra.fields:Object.fromEntries(Object.entries(v.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**
	 *  Open the scratch map, creating it if this is its first use. Ordinary in every way
	 *  except that [`store_list_maps`] hides it and startup wipes it.
	 */
	storeScratchMap: () => __TAURI_INVOKE<MapMeta>("store_scratch_map").then((v) => (({...v,extra:({...v.extra,fields:v.extra.fields==null?v.extra.fields:Object.fromEntries(Object.entries(v.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Delete a map and all its data permanently. */
	storeDeleteMap: (id: string) => __TAURI_INVOKE<null>("store_delete_map", { id }),
	/**
	 *  Apply a partial update to a map's metadata. `None` fields are left unchanged.
	 *  Returns a mutation result when the open map's field definitions changed.
	 */
	storeUpdateMapMeta: (id: string, patch: MapMetaPatch_Deserialize) => __TAURI_INVOKE<MutationResult | null>("store_update_map_meta", { id, patch: ({...patch,scoreBounds:patch.scoreBounds==null?patch.scoreBounds:patch.scoreBounds,extra:patch.extra==null?patch.extra:({...patch.extra,fields:patch.extra.fields==null?patch.extra.fields:Object.fromEntries(Object.entries(patch.extra.fields).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) }).then((v) => (v==null?v:({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**
	 *  Update `last_opened_at` to the current timestamp. Used to sort the map
	 *  list by recency in the dashboard.
	 */
	storeTouchMapOpened: (mapId: string) => __TAURI_INVOKE<null>("store_touch_map_opened", { mapId }),
	/**  Rename a folder across all maps that reference it. */
	storeRenameFolder: (from: string, to: string) => __TAURI_INVOKE<null>("store_rename_folder", { from, to }),
	/**  Delete a folder, moving its maps to the root level. */
	storeDeleteFolder: (name: string) => __TAURI_INVOKE<null>("store_delete_folder", { name }),
	/**  Return aggregate database statistics: counts, file size, and configuration. */
	storeDbStats: () => __TAURI_INVOKE<DbStats>("store_db_stats"),
	/**
	 *  Parse a file (JSON or ZIP of JSONs) and return a preview of each map found,
	 *  without persisting anything. Call [`bulk_import_confirm`] to import the maps.
	 */
	bulkImportPreview: (path: string) => __TAURI_INVOKE<ImportPreviewEntry[]>("bulk_import_preview", { path }),
	/**
	 *  Import the maps at `selected_indices` from a previously previewed file.
	 *  Emits `bulk-import-progress` per map.
	 */
	bulkImportConfirm: (path: string, selectedIndices: number[]) => __TAURI_INVOKE<ImportedMapInfo[]>("bulk_import_confirm", { path, selectedIndices }),
	/**
	 *  Discard the previewed import without importing. Call when the user cancels the
	 *  import dialog.
	 */
	bulkImportCancel: () => __TAURI_INVOKE<null>("bulk_import_cancel"),
	/**
	 *  Parse a file and return field-level statistics and preview positions for the
	 *  editor import dialog. Call [`store_import_file`] to commit the import.
	 */
	storeImportPreview: (path: string) => __TAURI_INVOKE<EditorImportPreview>("store_import_preview", { path }).then((v) => (({...v,bounds:v.bounds==null?v.bounds:v.bounds.map(i=>i)}) as typeof v)),
	/**
	 *  Parse pasted text (JSON or CSV) and stage it for preview. Works like
	 *  [`store_import_preview`] but reads from a string instead of a file.
	 */
	storeImportPastePreview: (text: string) => __TAURI_INVOKE<EditorImportPreview>("store_import_paste_preview", { text }).then((v) => (({...v,bounds:v.bounds==null?v.bounds:v.bounds.map(i=>i)}) as typeof v)),
	/**
	 *  Return one staged (not yet imported) location by its preview `index`, for
	 *  read-only preview in the editor.
	 */
	storeImportStagedLocation: (index: number) => __TAURI_INVOKE<Location>("store_import_staged_location", { index }),
	/**
	 *  Commit a previously previewed editor import into the open map, optionally
	 *  dropping fields in `dropped_fields` (e.g. `"heading"`, `"extra.countryCode"`)
	 *  and/or applying `tag_name` to every imported location.
	 */
	storeImportFile: (droppedFields: string[], tagName: string | null) => __TAURI_INVOKE<EditorImportResult>("store_import_file", { droppedFields, tagName }).then((v) => (({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}) as typeof v)),
	/**  Export locations as a `{name, customCoordinates}` JSON file, including tags and field defs. */
	storeExportJson: (opts: ExportOpts) => __TAURI_INVOKE<string>("store_export_json", { opts }),
	/**  Export locations as a minimal lat/lng CSV file. */
	storeExportCsv: (selector: Selector) => __TAURI_INVOKE<string>("store_export_csv", { selector }),
	/**
	 *  Export locations as a GeoJSON FeatureCollection of Point features.
	 *  Each feature carries its tag names in `properties.tags`.
	 */
	storeExportGeojson: (selector: Selector, tagsJson: string) => __TAURI_INVOKE<string>("store_export_geojson", { selector, tagsJson }),
	/**  Move a temp export file to `dest_path` and remove the temp source. */
	storeSaveExportFile: (srcPath: string, destPath: string) => __TAURI_INVOKE<null>("store_save_export_file", { srcPath, destPath }),
	/**
	 *  Export every map as a ZIP of JSON files. Duplicate map names get a numeric suffix.
	 *  Emits `bulk-export-progress` per map.
	 */
	storeExportBulkZip: () => __TAURI_INVOKE<string>("store_export_bulk_zip"),
	/**
	 *  Create a temp session directory for binary uploads. Files written into it are
	 *  packaged by [`store_upload_finish`].
	 */
	storeUploadBegin: () => __TAURI_INVOKE<string>("store_upload_begin"),
	/**
	 *  Package an upload session's files into a single output and remove the session
	 *  directory. Returns a temp path for [`store_save_export_file`].
	 */
	storeUploadFinish: (sessionDir: string) => __TAURI_INVOKE<string>("store_upload_finish", { sessionDir }),
	/**  Remove an abandoned upload session dir (e.g. cancelled operation). */
	storeUploadAbort: (sessionDir: string) => __TAURI_INVOKE<null>("store_upload_abort", { sessionDir }),
	/**
	 *  Commit the map's uncommitted changes. Returns the new commit ID. `message`
	 *  defaults to a generated `+a -r ~m` summary. Clears undo/redo.
	 */
	storeCommit: (mapId: string, message: string | null) => __TAURI_INVOKE<CommitResult>("store_commit", { mapId, message }).then((v) => (({...v,status:({...v.status,delta:({...v.status.delta,added:v.status.delta.added.map(i=>i),updated:v.status.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.status.values,fieldDefs:v.status.values.fieldDefs==null?v.status.values.fieldDefs:Object.fromEntries(Object.entries(v.status.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})}) as typeof v)),
	/**  List all commits for a map, newest first. */
	storeListCommits: (mapId: string) => __TAURI_INVOKE<CommitInfo[]>("store_list_commits", { mapId }),
	/**
	 *  Restore a map to the state captured by a previous commit. The caller must reopen
	 *  the map afterwards (undo/redo is cleared).
	 */
	storeCheckoutCommit: (mapId: string, commitId: string) => __TAURI_INVOKE<null>("store_checkout_commit", { mapId, commitId }),
	/**  Read a single commit's delta (created and removed locations). */
	storeGetCommitDelta: (mapId: string, commitId: string) => __TAURI_INVOKE<CommitDelta>("store_get_commit_delta", { mapId, commitId }).then((v) => (({...v,created:v.created.map(i=>i),removed:v.removed.map(i=>i)}) as typeof v)),
	/**  Record a panorama visit. The history is capped; oldest entries are evicted when full. */
	storeSeenWrite: (entry: SeenWriteEntry) => __TAURI_INVOKE<null>("store_seen_write", { entry }),
	/**  Returns a page of seen entries, newest first, with optional filtering. */
	storeSeenList: (limit: number, offset: number, filter: SeenFilter | null, thumbnails: boolean) => __TAURI_INVOKE<SeenEntry[]>("store_seen_list", { limit, offset, filter, thumbnails }).then((v) => (v.map(i=>i) as typeof v)),
	/**  Returns the total number of seen entries matching the filter (for pagination). */
	storeSeenCount: (filter: SeenFilter | null) => __TAURI_INVOKE<number>("store_seen_count", { filter }),
	/**  Return all distinct country codes in the seen history, sorted alphabetically. */
	storeSeenCountries: () => __TAURI_INVOKE<string[]>("store_seen_countries"),
	/**  Returns all distinct maps that have seen entries, with resolved display names. */
	storeSeenMaps: () => __TAURI_INVOKE<SeenMapInfo[]>("store_seen_maps"),
	/**  Deletes all seen history entries. */
	storeSeenClear: () => __TAURI_INVOKE<null>("store_seen_clear"),
	/**  Create a new review session from a frozen worklist of location IDs. */
	storeReviewCreate: (session: ReviewCreate) => __TAURI_INVOKE<ReviewSession>("store_review_create", { session }),
	/**  Look up the most recent active review session for a map and source key. */
	storeReviewGet: (mapId: string, sourceKey: string) => __TAURI_INVOKE<ReviewSession | null>("store_review_get", { mapId, sourceKey }),
	/**  List review sessions for a map, newest first. Optionally filter by `status`. */
	storeReviewList: (mapId: string, status: string | null) => __TAURI_INVOKE<ReviewSession[]>("store_review_list", { mapId, status }),
	/**  Apply a partial update to a review session. */
	storeReviewUpdate: (update: ReviewUpdate) => __TAURI_INVOKE<null>("store_review_update", { update }),
	/**  Delete a review session. */
	storeReviewDelete: (id: string) => __TAURI_INVOKE<null>("store_review_delete", { id }),
	/**  List every saved selection rule (name, color, date), without their selector trees. */
	storeListSavedSelections: () => __TAURI_INVOKE<SavedSelectionInfo[]>("store_list_saved_selections"),
	/**  Fetch the full saved selection rules for the given `ids`, including their selector trees. */
	storeGetSavedSelections: (ids: string[]) => __TAURI_INVOKE<SavedSelection[]>("store_get_saved_selections", { ids }),
	/**  Save a new selection rule. */
	storeSaveSelection: (name: string, selector: Selector, tagNames: { [key in number]: string }, color: [number, number, number]) => __TAURI_INVOKE<SavedSelection>("store_save_selection", { name, selector, tagNames, color }),
	/**  Delete a saved selection rule by `id`. */
	storeDeleteSavedSelection: (id: string) => __TAURI_INVOKE<null>("store_delete_saved_selection", { id }),
	/**
	 *  Import saved selections from the pre-0.10 localStorage format. No-op when
	 *  rules already exist. Returns the number of rules imported.
	 */
	storeImportLegacySavedSelections: (json: string) => __TAURI_INVOKE<number>("store_import_legacy_saved_selections", { json }),
	/**  Get all local-to-remote id mapping rows for a linked map. */
	remoteMappingGet: (provider: string, mapId: string) => __TAURI_INVOKE<RemoteMappingRow[]>("remote_mapping_get", { provider, mapId }),
	/**  Insert or update local-to-remote id mapping rows for a linked map. */
	remoteMappingUpsert: (provider: string, mapId: string, rows: RemoteMappingRow[]) => __TAURI_INVOKE<null>("remote_mapping_upsert", { provider, mapId, rows }),
	/**  Remove specific mapping rows by `local_ids` for a linked map. */
	remoteMappingDelete: (provider: string, mapId: string, localIds: number[]) => __TAURI_INVOKE<null>("remote_mapping_delete", { provider, mapId, localIds }),
	/**  Drop all mapping rows for a linked map (unlink). */
	remoteMappingClear: (provider: string, mapId: string) => __TAURI_INVOKE<null>("remote_mapping_clear", { provider, mapId }),
	/**
	 *  Reconcile a linked map against its remote, pushing local changes and pulling
	 *  remote ones. Returns the creates, updates, and deletes for each side to apply.
	 */
	syncReconcile: (provider: string, mapId: string, remoteMapId: string, apiKey: string | null, firstSync: FirstSyncMode | null, resolutions: ([string, ResolutionSide])[] | null) => __TAURI_INVOKE<SyncReconcileResult>("sync_reconcile", { provider, mapId, remoteMapId, apiKey, firstSync, resolutions }).then((v) => (({...v,conflicts:v.conflicts.map(i=>({...i,local:i.local==null?i.local:i.local,remote:i.remote==null?i.remote:i.remote})),pullUpdates:v.pullUpdates.map(i=>({...i,patch:({...i.patch,lat:i.patch.lat==null?i.patch.lat:i.patch.lat,lng:i.patch.lng==null?i.patch.lng:i.patch.lng,heading:i.patch.heading==null?i.patch.heading:i.patch.heading,pitch:i.patch.pitch==null?i.patch.pitch:i.patch.pitch,zoom:i.patch.zoom==null?i.patch.zoom:i.patch.zoom})}))}) as typeof v)),
	/**
	 *  Open the GeoGuessr sign-in window and wait for authentication to complete.
	 *  Returns the signed-in nickname.
	 */
	geoguessrLogin: () => __TAURI_INVOKE<string>("geoguessr_login"),
	/**  The signed-in user, or `None` when there is no session (or it was rejected). */
	geoguessrMe: () => __TAURI_INVOKE<GgUser | null>("geoguessr_me"),
	/**  Sign out of GeoGuessr and clear the stored session. */
	geoguessrLogout: () => __TAURI_INVOKE<null>("geoguessr_logout"),
	/**  Local-only check: is a token stored? Says nothing about its validity. */
	geoguessrHasSession: () => __TAURI_INVOKE<boolean>("geoguessr_has_session"),
	/**
	 *  Generate locations from a Vali map definition (JSON/JSONC text). Missing country
	 *  data is auto-downloaded like the Vali CLI. Returns the generated locations.
	 */
	valiGenerate: (definition: string) => __TAURI_INVOKE<ValiLocation[]>("vali_generate", { definition }).then((v) => (v.map(i=>({...i,zoom:i.zoom==null?i.zoom:i.zoom,pitch:i.pitch==null?i.pitch:i.pitch})) as typeof v)),
	/**  Download Vali coverage data. `country` = code/continent alias/None for all. */
	valiDownload: (country: string | null, full: boolean, updates: boolean) => __TAURI_INVOKE<null>("vali_download", { country, full, updates }),
	/**  Cancel an in-flight vali generate or download. */
	valiCancel: () => __TAURI_INVOKE<void>("vali_cancel"),
	/**  Subdivision weights for a country (JSON text, same shape as `vali subdivisions`). */
	valiSubdivisions: (country: string) => __TAURI_INVOKE<string>("vali_subdivisions", { country }),
	/**
	 *  Country codes Vali has coverage data for, i.e. the set `vali download` iterates
	 *  when no country is given. Display names are the caller's job.
	 */
	valiCountries: () => __TAURI_INVOKE<string[]>("vali_countries"),
	/**
	 *  Countries whose downloaded coverage data is older than the remote copy. Object metadata
	 *  only -- nothing is fetched. Errors while offline, which callers should read as "unknown"
	 *  rather than "up to date".
	 */
	valiDataStatus: () => __TAURI_INVOKE<ValiCountryStatus[]>("vali_data_status").then((v) => (v.map(i=>i) as typeof v)),
	/**
	 *  Download exactly the countries `vali_data_status` reports as behind. No-op when nothing
	 *  is stale, so the caller can fire it without checking first.
	 */
	valiDownloadStale: () => __TAURI_INVOKE<null>("vali_download_stale"),
	/**
	 *  Start a procedure run over the open map's locations. Returns immediately with
	 *  the run id. Emits `procedure-progress` and `procedure-result` as work completes.
	 */
	procedureRun: (providers: ProviderDecl[], force: boolean) => __TAURI_INVOKE<number>("procedure_run", { providers, force }),
	/**
	 *  Run providers over caller-supplied `rows` and return them as modified. Does not
	 *  affect the open map. `cancel` is a token for [`procedure_query_cancel`].
	 */
	procedureRunRows: (providers: ProviderDecl[], force: boolean, rows: Location[], cancel: number | null) => __TAURI_INVOKE<RowsRun>("procedure_run_rows", { providers, force, rows: rows.map(i=>i), cancel }).then((v) => (({...v,rows:v.rows.map(i=>i)}) as typeof v)),
	/**  Stop a run before its next batch. Already-applied patches stay applied. */
	procedureCancel: (runId: number) => __TAURI_INVOKE<null>("procedure_cancel", { runId }),
	/**
	 *  Run a procedure's read-only `query` export. `input` and the result are defined
	 *  by the procedure module. `cancel` is a token for [`procedure_query_cancel`].
	 */
	procedureQuery: (entry: string, input: string, config: string | null, cancel: number | null) => __TAURI_INVOKE<string>("procedure_query", { entry, input, config, cancel }),
	/**  Cancel a running procedure query by its `cancel` token. */
	procedureQueryCancel: (cancel: number) => __TAURI_INVOKE<null>("procedure_query_cancel", { cancel }),
};

/** Events */
export const events = {
	bulkExportProgress: makeEvent<ExportProgress>("bulk-export-progress"),
	bulkImportProgress: makeEvent<ImportProgress>("bulk-import-progress"),
	procedureProgress: makeEvent<ProcedureProgress>("procedure-progress"),
	procedureResult: makeEvent<ProcedureResult>("procedure-result"),
	sidecarDone: makeEvent<SidecarDone>("sidecar-done"),
	sidecarInstallProgress: makeEvent<SidecarProgress>("sidecar-install-progress"),
	sidecarLine: makeEvent<SidecarLine>("sidecar-line"),
	sidecarLog: makeEvent<SidecarLog>("sidecar-log"),
	storeExternalMutation: makeEvent<ExternalMutation>("store-external-mutation", (v) => ({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})}), (v) => ({...v,delta:({...v.delta,added:v.delta.added.map(i=>i),updated:v.delta.updated.map(i=>({...i,lng:i.lng==null?i.lng:i.lng,lat:i.lat==null?i.lat:i.lat,heading:i.heading==null?i.heading:i.heading}))}),values:({...v.values,fieldDefs:v.values.fieldDefs==null?v.values.fieldDefs:Object.fromEntries(Object.entries(v.values.fieldDefs).map(([k,v])=>[k,({...v,comparison:v.comparison==null?v.comparison:v.comparison})]))})})),
	storeWarning: makeEvent<StoreWarning>("store-warning"),
	updateProgress: makeEvent<UpdateProgress>("update-progress"),
	valiProgress: makeEvent<ValiProgress>("vali-progress"),
};

/* Types */
export type AnonIssueRef = {
	number: number,
	url: string,
	/**
	 *  Grants read access to this one issue's relayed comments. Not a credential for anything
	 *  else, which is why it is safe to keep in local storage.
	 */
	token: string,
};

/**  An image the reporter attached, once it is somewhere the issue can point at. */
export type AttachmentRef = {
	url: string,
	/**
	 *  Alt text for the reference. The worker decides it -- a client-supplied name reaches the
	 *  rendered issue.
	 */
	name: string,
};

/**  How a page of rows is cut into procedure calls. */
export type BatchMode = { mode: "chunk"; size: number } | { mode: "perRow" } | 
/**
 *  Group rows by a row field; the procedure sees one representative per distinct
 *  value and its patch fans back out to every row sharing it. v1 key: `panoId`.
 */
{ mode: "dedupeBy"; key: string };

export type CameraType = "gen1" | "gen2" | "gen4" | "badcam" | "tripod" | "trekker";

/**
 *  A swap-removal from a render cell. JS must move the last element into `cell_index`
 *  and pop the array to mirror the Rust-side swap-remove.
 */
export type CellRemoval = {
	cell: string,
	cellIndex: number,
	id: number,
};

/**
 *  Per-field columns of the selected set. One value per row per field, `null` where a
 *  row lacks it; `"tags"` is a column of tag-id arrays.
 */
export type Columns = unknown[][];

/**
 *  A commit's created and removed locations. An updated location appears in both
 *  `created` (new version) and `removed` (old version).
 */
export type CommitDelta = {
	created: Location[],
	removed: Location[],
};

/**  Added, removed, and modified counts for a commit. */
export type CommitDiff = {
	added: number,
	removed: number,
	modified: number,
};

/**  Metadata for a single commit. */
export type CommitInfo = {
	id: string,
	mapId: string,
	parentId: string | null,
	message: string | null,
	treeHash: string | null,
	locationCount: number,
	createdAt: string,
} & CommitDiff;

/**  The new commit's ID and the resulting state update. */
export type CommitResult = {
	id: string,
	status: MutationResult,
};

/**
 *  How a field's values are compared when measuring how strongly it separates
 *  groups (selection disambiguation). The only un-inferrable property a field can
 *  declare is circularity (heading/azimuth=360, hour-of-day=24, month=12);
 *  everything else is inferred from `ExtraFieldType`.
 */
export type ComparisonType = { type: "linear" } | { type: "circular"; period: number } | { type: "categorical" };

export type Conflict = {
	key: string,
	kind: ConflictKind,
	/**  Base value is not persisted (only its hash), so conflicts surface local vs remote. */
	local: NormalizedSyncLocation | null,
	remote: NormalizedSyncLocation | null,
};

export type ConflictKind = 
/**  Both sides modified the same location differently. */
"update-update" | 
/**  One side deleted while the other modified. */
"delete-update" | 
/**  Both sides added the same identity with different content (hash collision only). */
"add-add";

/**  Result of a cross-map location copy. `target_name` feeds the toast. */
export type CopyToMapResult = {
	copied: number,
	skipped: number,
	targetName: string,
};

/**  The active and default data-folder paths, plus whether a custom override is in effect. */
export type DataLocation = {
	path: string,
	/**  OS default, ignoring any override -- backs the "reset" affordance. */
	default_path: string,
	is_custom: boolean,
};

/**  A calendar component to group dates by. */
export type DatePart = "year" | "yearMonth" | "day" | "monthOfYear" | "hourOfDay";

/**  Aggregate database statistics for the debug panel. */
export type DbStats = {
	maps: number,
	locations: number,
	tags: number,
	commits: number,
	dbSizeBytes: number,
	journalMode: string,
	foreignKeys: boolean,
};

/**  What the user needs in order to authorize: the code to type and where to type it. */
export type DeviceCodeInfo = {
	userCode: string,
	verificationUri: string,
	/**  Seconds until `user_code` stops working. */
	expiresIn: number,
};

/**
 *  Preview data for importing a file into the currently open map.
 *  Unlike bulk import, this shows per-field counts so the user can
 *  selectively drop fields (heading, panoId, etc.) before importing.
 */
export type EditorImportPreview = {
	locationCount: number,
	tags: Tag[],
	fields: FieldCount[],
	warnings: string[],
	/**  Temp-file path to preview positions: interleaved LE f32 `[lng, lat]` pairs. */
	previewPositionsPath: string,
	/**  `[west, south, east, north]` bounding box of the import, for map auto-focus. */
	bounds: [number, number, number, number] | null,
	/**
	 *  True when this import exceeds `IMPORT_AUTOCOMMIT_THRESHOLD` and will be
	 *  committed automatically (not undoable). Drives the import warning modal.
	 */
	willAutoCommit: boolean,
};

/**
 *  Combined result of an editor import: the mutation delta (for render pipeline)
 *  plus import-specific metadata.
 */
export type EditorImportResult = {
	importedCount: number,
	warnings: string[],
	/**  True when the import was large enough to autocommit; the caller commits it. */
	autoCommit: boolean,
	/**  Settings carried by the import (`extra.settings`) */
	settings: { [key in string]: any },
} & MutationResult;

/**
 *  The engine-owned values JS mirrors into its state, each `None` when unchanged since
 *  it last shipped. The open-time form ([`super::StoreStatus`]) has every field present.
 *  The JS mirror's type and merge are derived from this struct.
 */
export type EngineValues = {
	locationCount: number | null,
	canUndo: boolean | null,
	canRedo: boolean | null,
	/**  Every tag's count, when any count moved. */
	tagCounts: { [key in number]: number } | null,
	/**
	 *  The whole registry, when any tag was created, edited, deleted, or flipped visible.
	 *  Includes soft-deleted ghosts (visible=false, kept for undo revival).
	 */
	tags: { [key in number]: Tag } | null,
	/**
	 *  The whole extra-field registry (`MapMeta.extra.fields` mirror), when a key was
	 *  seen for the first time, erased, or the user edited a definition.
	 */
	fieldDefs: { [key in string]: ExtraFieldDef } | null,
};

/**
 *  Configuration for JSON export. Controls which fields are included and
 *  whether the export covers all locations or a specific selection.
 */
export type ExportOpts = {
	exportZoom: boolean,
	exportUnpanned: boolean,
	exportExtras: boolean,
	/**  Which locations to export. */
	selector: Selector,
	mapName: string,
	/**
	 *  Serialized `{id: {name, color}}` tag definitions from the store, used to
	 *  convert numeric tag IDs back to human-readable names in the output.
	 */
	tagsJson: string,
	extraFieldsJson: string | null,
};

/**
 *  Progress event emitted per-map during bulk export, consumed by the frontend
 *  to drive a progress indicator.
 */
export type ExportProgress = {
	current: number,
	total: number,
	mapName: string,
};

/**  A mutation another window made to a map this window may have open, routed by `map_id`. */
export type ExternalMutation = {
	mapId: string,
} & MutationResult;

/**
 *  Schema definition for a single `Location.extra` field. Stored in the map's
 *  `extra.fields` JSON. For enum types, `values` lists valid options and `labels`
 *  provides display names.
 */
export type ExtraFieldDef = {
	type: ExtraFieldType,
	label: string | null,
	values: string[] | null,
	labels: { [key in string]: string } | null,
	/**
	 *  Optional override for how this field is compared during disambiguation.
	 *  `None` => inferred from `field_type` on the analysis side.
	 */
	comparison: ComparisonType | null,
};

/**
 *  Type discriminant for `Location.extra` field definitions.
 *  Determines how the field is displayed and filtered in the UI.
 */
export type ExtraFieldType = "string" | "number" | "date" | "month" | "enum" | "array";

/**
 *  Field presence count for the editor import preview dialog, letting
 *  the user see which optional fields exist and decide which to keep/drop.
 */
export type FieldCount = {
	key: string,
	count: number,
};

/**
 *  A field-wide rewrite of the `extra` map. Patches are derived *per row*, which is what
 *  separates these from `store_update_locations`' explicit patch list.
 */
export type FieldOp = 
/**
 *  Rename `from` into `to`. Merge is the same operation -- rename is just the case
 *  where nothing holds `to` -- so `winner` decides only where a row holds both.
 */
{ kind: "move"; from: string; to: string; winner: MergeWinner } | 
/**  Drop `keys` from every row that has them. */
{ kind: "delete"; keys: string[] } | 
/**
 *  Assign `value` to `key` on every row where it differs. A writable built-in key
 *  (`heading`, `pitch`, `zoom`) patches its column; anything else writes `extra`.
 */
{ kind: "set"; key: string; value: unknown } | 
/**
 *  Assign `key = expr(row)` per row. A row where the expression cannot evaluate (a
 *  missing or non-numeric field, a non-finite result) is reported back by id.
 */
{ kind: "expr"; key: string; expr: string };

/**  The op's outcome for the caller: the mutation plus what its message needs. */
export type FieldOpResult = {
	mutation: MutationResult,
	/**  Rows the op patched. */
	changed: number,
	/**  Rows an expression could not evaluate. */
	failed: number[],
};

/**
 *  A filter's predicate: the operator with its operands. Single source of truth: specta
 *  renders the tagged union, so the TS `FilterOp` type and `OP_LABELS` derive from it.
 *  The range operators can read a date in the row's own timezone (`tzLocal`); the
 *  `between_*` shapes bucket a timestamp by month-day or time-of-day before comparing.
 */
export type FilterOp = { op: "has" } | { op: "nothas" } | { op: "eq"; value: any } | { op: "neq"; value: any } | { op: "contains"; value: any } | { op: "notcontains"; value: any } | { op: "gt"; value: any; tzLocal?: boolean } | { op: "lt"; value: any; tzLocal?: boolean } | { op: "gte"; value: any; tzLocal?: boolean } | { op: "lte"; value: any; tzLocal?: boolean } | { op: "between"; lo: any; hi: any; tzLocal?: boolean } | { op: "between_anyyear"; lo: string; hi: string; tzLocal?: boolean } | { op: "between_anytime"; lo: string; hi: string; tzLocal?: boolean };

/**
 *  First-sync seeding when both sides already have pins. Only meaningful on the first sync
 *  (empty mapping); afterwards it's plain three-way. `Merge` never deletes.
 */
export type FirstSyncMode = "merge" | "mirrorFromRemote" | "mirrorFromLocal";

/**  Reverse geocode result: nearest populated place to a coordinate. */
export type GeoResult = {
	city: string,
	/**  First-level administrative division (state, province, region). */
	admin: string,
	country: string,
	/**  ISO 3166-1 alpha-2 (e.g. "US", "FR"). */
	country_code: string,
};

/**  The signed-in GeoGuessr account. */
export type GgUser = {
	id: string,
	nick: string,
	/**  Avatar pin path (e.g. `pin/<hash>.png`), served under `/images/` on geoguessr.com. */
	pin: string | null,
};

export type GhUser = {
	login: string,
	avatarUrl: string | null,
};

/**
 *  Summary of a single map found during bulk import preview.
 *  Shown in the import dialog so the user can select which maps to import.
 */
export type ImportPreviewEntry = {
	name: string,
	folder: string | null,
	locationCount: number,
	tagCount: number,
	warnings: string[],
};

/**
 *  Progress event emitted per-map during bulk import, consumed by the frontend
 *  to drive a progress indicator.
 */
export type ImportProgress = {
	current: number,
	total: number,
	mapName: string,
};

/**  Result returned per map after a successful bulk import. */
export type ImportedMapInfo = {
	id: string,
	name: string,
	locationCount: number,
	tagCount: number,
};

export type IssueComment = {
	author: string,
	body: string,
	/**  ISO-8601, as GitHub returns it. */
	createdAt: string,
};

export type IssueRef = {
	number: number,
	url: string,
};

export type IssueState = "open" | "closed";

/**
 *  What became of a report, and what has been said on it. One shape for both transports so a
 *  signed-in and an anonymous report render identically.
 */
export type IssueThread = {
	state: IssueState,
	/**
	 *  `completed`, `not_planned` or `reopened`. Absent on an open issue, and on issues closed
	 *  before GitHub recorded a reason.
	 */
	stateReason: string | null,
	comments: IssueComment[],
};

/**  How a field value becomes a group key. Wire-mirrors the JS `KeySpec`. */
export type KeySpec = 
/**  String value of the field (enum/string/month "YYYY-MM"/number). */
{ kind: "value" } | 
/**  Equal-width numeric bins. */
{ kind: "numericBin"; binning: NumericBinning } | 
/**  Calendar component of a date (epoch seconds) or month ("YYYY-MM") field. */
{ kind: "datePart"; part: DatePart; tzLocal: boolean };

/**
 *  A single Street View location on a map.
 * 
 *  This is the atomic unit of data in the system. Locations are stored columnar
 *  in Arrow IPC on disk and addressed by `id` everywhere. The `id` is unique
 *  within a map and assigned by the store's monotonic allocator.
 */
export type Location = {
	/**
	 *  Monotonically increasing within a map. Zero is a sentinel meaning
	 *  "not yet assigned" (used during import before IDs are allocated).
	 */
	id: number,
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	panoId: string | null,
	/**  See [`LocationFlags`]. */
	flags: number,
	/**  Tag IDs applied to this location. References `Tag.id`. */
	tags: number[],
	/**  Arbitrary key-value metadata */
	extra: { [key in string]: unknown } | null,
	/**  Unix timestamp (seconds) */
	createdAt: number,
	modifiedAt: number | null,
};


/**
 *  Partial location update from JS. `None` fields are unchanged; `Some(None)` on
 *  nullable fields (panoId, extra, modifiedAt) explicitly sets the field to null.
 *  `extra` is a JSON Merge Patch (RFC 7386): keys shallow-merge, null values delete.
 */
export type LocationPatch_Deserialize = {
	lat?: number | null,
	lng?: number | null,
	heading?: number | null,
	pitch?: number | null,
	zoom?: number | null,
	panoId?: string | null,
	flags?: number | null,
	tags?: number[] | null,
	extra?: { [key in string]: unknown } | null,
	createdAt?: number | null,
	modifiedAt?: number | null,
};

/**
 *  Partial location update from JS. `None` fields are unchanged; `Some(None)` on
 *  nullable fields (panoId, extra, modifiedAt) explicitly sets the field to null.
 *  `extra` is a JSON Merge Patch (RFC 7386): keys shallow-merge, null values delete.
 */
export type LocationPatch = {
	lat: number | null,
	lng: number | null,
	heading: number | null,
	pitch: number | null,
	zoom: number | null,
	panoId: string | null,
	flags: number | null,
	tags: number[] | null,
	extra: { [key in string]: unknown } | null,
	createdAt: number | null,
	modifiedAt: number | null,
};

/**
 *  Top-level `extra` JSON blob on a map row. Currently only holds field definitions,
 *  but structured as an object to allow future extensions.
 */
export type MapExtra = {
	fields: { [key in string]: ExtraFieldDef } | null,
};

/**
 *  Action performed by a per-map key binding on the active location.
 *  New action kinds (e.g. copy-to-map) are added as variants here.
 */
export type MapKeyAction = { type: "applyTag"; tagId: number } | { type: "copyToMap"; mapId: string };

/**
 *  One user-defined per-map key binding. `key` is a combo string in the same
 *  canonical format as global hotkey bindings (e.g. "m", "Mod+Shift+x").
 */
export type MapKeyBinding = {
	key: string,
	action: MapKeyAction,
};

/**  Full metadata for a map. */
export type MapMeta = {
	id: string,
	name: string,
	description: string,
	folder: string | null,
	settings: MapSettings,
	scoreBounds: ScoreBounds,
	extra: MapExtra,
	tags: { [key in string]: Tag },
	labels: string[],
	locationCount: number,
	createdAt: string,
	updatedAt: string,
	lastOpenedAt: string | null,
};


/**
 *  Partial update for map metadata. `None` fields are left unchanged.
 *  Setting `folder` to null moves the map to root.
 */
export type MapMetaPatch_Deserialize = {
	name?: string | null,
	description?: string | null,
	folder?: string | null,
	settings?: MapSettings | null,
	scoreBounds?: ScoreBounds | null,
	extra?: MapExtra | null,
	tags?: { [key in string]: Tag } | null,
	labels?: string[] | null,
};

/**
 *  Partial update for map metadata. `None` fields are left unchanged.
 *  Setting `folder` to null moves the map to root.
 */
export type MapMetaPatch = {
	name: string | null,
	description: string | null,
	folder: string | null,
	settings: MapSettings | null,
	scoreBounds: ScoreBounds | null,
	extra: MapExtra | null,
	tags: { [key in string]: Tag } | null,
	labels: string[] | null,
};

/**
 *  Per-map editor preferences. Controls Street View lookup behavior (official vs
 *  unofficial, camera type filters), export defaults, and metadata enrichment.
 */
export type MapSettings = {
	pointAlongRoad?: boolean,
	preferDirection?: string | null,
	preferOfficial?: boolean,
	preferHigherQuality?: boolean,
	onlyOfficial?: boolean,
	cameraTypes?: string[] | null,
	defaultPanoId?: boolean,
	exportZoom?: boolean,
	exportUnpanned?: boolean,
	exportExtras?: boolean,
	searchRadius?: number | null,
	enrichMetadata?: boolean,
	enrichFields?: string[] | null,
	keyBindings?: MapKeyBinding[],
	/**  Virtual tag-tree nodes keyed by full slash path. Tree-view only. */
	virtualTags?: { [key in string]: VirtualTag },
	/**
	 *  Tag aliases: a second tree location (full slash path) -> the real tag id shown
	 *  there. Tree-view only; clicking the alias leaf toggles the real tag.
	 */
	aliases?: { [key in string]: number },
	/**
	 *  Which member of a duplicate group survives a merge: a `field_expr` scoring the
	 *  location, highest wins. `None` (or blank) keeps the built-in ranking.
	 */
	duplicateScore?: string | null,
	/**
	 *  The order a review pass walks its worklist: a `field_expr` scoring the location,
	 *  highest first. `None` (or blank) keeps the order the selection resolved in.
	 */
	reviewOrder?: string | null,
};

/**  When a move target already holds a value, which side survives. */
export type MergeWinner = "from" | "to";

/**
 *  What one mutation changed, and nothing else. `values` are merged into the JS state
 *  mirror (an untouched slice keeps its reference and its subscribers sleep); `delta`
 *  and `selection_sync` are operations applied once to the render buffers.
 */
export type MutationResult = {
	version: number,
	delta: RenderDelta,
	selectionSync: SelectionSync | null,
	values: EngineValues,
};

/**
 *  The syncable contract: the only fields that participate in diffing. Everything else is
 *  owned by exactly one side and would register as a phantom change.
 */
export type NormalizedSyncLocation = {
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	panoId: string | null,
	/**  Remote-meaningful bits only; virtual bits are stripped. */
	flags: number,
	/**  Tag names, deduped and sorted. Empty for providers with no tag support. */
	tags: string[],
};

/**  Equal-width bin sizing. `count` derives the width from the data range; `width` fixes it. */
export type NumericBinning = { by: "count"; n: number } | { by: "width"; w: number };

/**
 *  One partition group: a stable key, the ids it holds, and (numeric bins only) the
 *  `[lo, hi]` bounds so JS can rebuild a live Filter for whole-map gradients.
 */
export type PartitionBucket = {
	key: string,
	ids: number[],
	bin: [number, number] | null,
};


/**
 *  A published build of a plugin, pinned to the commit its files live at. Carries only
 *  what picking a build needs -- the rest comes from the manifest at `git_ref`.
 */
export type PluginBuild_Deserialize = {
	version: string,
	ref: string,
	minAppVersion: string | null,
};

/**
 *  A published build of a plugin, pinned to the commit its files live at. Carries only
 *  what picking a build needs -- the rest comes from the manifest at `git_ref`.
 */
export type PluginBuild = {
	version: string,
	ref: string,
	minAppVersion?: string | null,
};


/**  Metadata for a user-installed plugin, read from `plugins/{id}/manifest.json`. */
export type PluginManifest_Deserialize = {
	id?: string,
	name?: string,
	description?: string,
	icon?: string,
	main?: string,
	/**  Enrichment procedure module this plugin ships, downloaded alongside `main`. */
	procedure?: string | null,
	version?: string,
	experimental?: boolean,
	comingSoon?: boolean,
	minAppVersion?: string | null,
	sidecar?: PluginSidecar_Deserialize | null,
	/**
	 *  Registry-only: prior builds an app under `min_app_version` can fall back to.
	 *  An installed manifest never carries these.
	 */
	builds?: PluginBuild_Deserialize[],
};

/**  Metadata for a user-installed plugin, read from `plugins/{id}/manifest.json`. */
export type PluginManifest = {
	id: string,
	name: string,
	description: string,
	icon: string,
	main: string,
	/**  Enrichment procedure module this plugin ships, downloaded alongside `main`. */
	procedure?: string | null,
	version: string,
	experimental?: boolean,
	comingSoon?: boolean,
	minAppVersion?: string | null,
	sidecar?: PluginSidecar | null,
	/**
	 *  Registry-only: prior builds an app under `min_app_version` can fall back to.
	 *  An installed manifest never carries these.
	 */
	builds?: PluginBuild[],
};


/**  A plugin's declared sidecar binary (downloaded from GitHub Releases on install). */
export type PluginSidecar_Deserialize = {
	name: string,
	version: string,
	/**  Expected SHA-256 hex digest of the platform-specific zip archive. */
	sha256: string | null,
};

/**  A plugin's declared sidecar binary (downloaded from GitHub Releases on install). */
export type PluginSidecar = {
	name: string,
	version: string,
	/**  Expected SHA-256 hex digest of the platform-specific zip archive. */
	sha256?: string | null,
};

/**
 *  GeoJSON-like polygon geometry. `coordinates` is the primary polygon (outer ring +
 *  optional holes). `extra_polygons` allows multipolygon selections (e.g., from GeoJSON import).
 */
export type PolygonGeometry = {
	coordinates: (([number, number])[])[],
	extraPolygons: ((([number, number])[])[])[] | null,
	properties?: any | null,
};

export type PresenceActivity = {
	details: string | null,
	state: string | null,
	largeImage: string | null,
	largeText: string | null,
	smallImage: string | null,
	smallText: string | null,
	/**  Unix seconds; Discord renders an "elapsed" timer counting up from here. */
	start: number | null,
};

export type ProcedureProgress = {
	runId: number,
	providerId: string,
	done: number,
	total: number,
	failed: number,
	/**
	 *  Rows counted as done without being worked, because they already held every field
	 *  the provider produces. Callers subtract these to report what a run actually did.
	 */
	skipped: number,
	finished: boolean,
};

/**
 *  What one page hands back to the caller: a `Collect` provider's answers, delivered
 *  instead of being written, and for every sink the rows that failed. Emitted only when
 *  there is something in it.
 */
export type ProcedureResult = {
	runId: number,
	providerId: string,
	entries: ResultEntry[],
	/**  Rows the procedure failed, or every row of a batch whose call failed. */
	failed: number[],
};

/**
 *  One provider as declared by the frontend. `fields` are the extra keys it produces
 *  and `requires` the keys it consumes; together they gate who waits for whom.
 */
export type ProviderDecl = {
	id: string,
	label?: string | null,
	/**  The procedure module: an absolute path, or `res://<rel>` for one bundled with the app. */
	entry?: string | null,
	fields?: string[],
	requires?: string[],
	invalidates?: { [key in string]: string[] },
	select: Selector,
	batch: BatchMode,
	sink?: Sink,
	rate?: RateSpec | null,
	retry?: RetrySpec | null,
	/**
	 *  Re-derive this provider's fields even on a run that is not forced. For an
	 *  operation whose whole point is to recompute one provider (pinning re-resolves the
	 *  panorama) rather than to fill in what is missing.
	 */
	force?: boolean | null,
	/**  Requests this provider may have in flight at once, summed over its instances. */
	inflight?: number | null,
	/**
	 *  Instances this provider may run at once. Declared only when the procedure
	 *  cannot run beside itself; throughput comes from `inflight`.
	 */
	instances?: number | null,
	/**
	 *  Provider-specific configuration, a JSON value as text. Passed through verbatim
	 *  inside the object the procedure's `configure` receives.
	 */
	config?: string | null,
};

/**
 *  A remote-originated create for JS to apply. `remote_id` is the handle its mapping row must
 *  carry once created (a positional push reindexes to its desired-document position).
 */
export type PullCreate = {
	fields: NormalizedSyncLocation,
	remoteId: number,
	hash: string,
};

/**  A remote-originated update for JS to apply to an existing local id. */
export type PullUpdate = {
	localId: number,
	patch: SyncPatch,
};

/**
 *  What one attempt charges the bucket: the call itself, or one per row in its batch
 *  (for APIs that bill multi-row requests per row).
 */
export type RateCost = "request" | "row";

/**  Token bucket: `units` calls per `per_ms` milliseconds, refilled continuously. */
export type RateSpec = {
	units: number,
	perMs: number,
	cost?: RateCost,
};

/**  One mapping row. `hash` is the plugin's content fingerprint (opaque text to us). */
export type RemoteMappingRow = {
	localId: number,
	/**  Remote ids can exceed u32 (observed ~1.2e10), so i64. */
	remoteId: number,
	hash: string,
};

/**
 *  Incremental render update sent to JS after a mutation: adds, patches, and removals.
 *  Every entry states the row's resulting selection state, so applying a delta is
 *  idempotent and the base cells and the selection overlay cannot drift apart.
 *  `full_reset` signals JS to discard all cell data and re-fetch via `store_fill_render_file`.
 */
export type RenderDelta = {
	added: RenderEntry[],
	updated: RenderPatchEntry[],
	removed: CellRemoval[],
	fullReset: boolean,
};

/**  A marker appended to a render cell: position, heading, and selection state. */
export type RenderEntry = {
	cell: string,
	id: number,
	lng: number,
	lat: number,
	heading: number,
	/**  `None` = drawn by the base layer, `Some(paint)` = drawn by the selection overlay. */
	sel: SelPaint | null,
	/**
	 *  The slot this row vacated when it crossed cells. Present only for a move, so JS
	 *  mirrors the swap-remove and carries the overlay entry across instead of inferring
	 *  a move from an unrelated removed/added pair.
	 */
	movedFrom: CellRemoval | null,
};

/**
 *  Update to an existing marker within its cell. Position and heading are `None` when
 *  unchanged; `sel` always states the row's current selection state, so a membership
 *  change with no movement is just a patch with no coordinates.
 */
export type RenderPatchEntry = {
	cell: string,
	cellIndex: number,
	lng: number | null,
	lat: number | null,
	heading: number | null,
	sel: SelPaint | null,
};

/**
 *  Parameters for a full render rebuild. `marker_style` ("arrow" or "pin") determines
 *  whether heading angles are written. The bounding box fields are currently unused
 *  (no viewport culling -- all locations are rendered).
 */
export type RenderRequest = {
	west?: number,
	south?: number,
	east?: number,
	north?: number,
	selectedIds?: number[] | null,
	markerStyle?: string,
	markerColor?: [number, number, number] | null,
};

/**  Which side won a resolved conflict; serialized as "local"/"remote". */
export type ResolutionSide = "local" | "remote";

/**
 *  One location's answer from a `Collect` provider: whatever its module emitted for
 *  that row, carried as text exactly as a patch would be.
 */
export type ResultEntry = {
	id: number,
	json: string,
};

/**  Retry only the listed HTTP statuses, up to `attempts` total tries. */
export type RetrySpec = {
	attempts: number,
	on: number[],
};

/**
 *  Parameters for creating a review session. `order` is the frozen worklist (must be
 *  non-empty); the cursor starts at its first id.
 */
export type ReviewCreate = {
	mapId: string,
	name: string,
	sourceKey: string,
	sourceProps: any,
	order: number[],
};

/**  A review session: a frozen worklist of locations with progress tracking. */
export type ReviewSession = {
	id: string,
	mapId: string,
	name: string,
	sourceKey: string,
	sourceProps: any,
	order: number[],
	reviewed: number[],
	cursorId: number,
	status: string,
	createdAt: string,
	updatedAt: string,
};

/**  Partial update for a review session. `None` fields are left unchanged. */
export type ReviewUpdate = {
	id: string,
	name?: string | null,
	cursorId: number | null,
	reviewed: number[] | null,
	ordering: number[] | null,
	status: string | null,
};

/**  Result of `store_collect`: locations returned inline, or a file path to read them from. */
export type Rows = { kind: "inline"; locations: Location[] } | { kind: "file"; path: string };

/**  Rows after a run over them, and the ids each provider failed. */
export type RowsRun = {
	rows: Location[],
	failed: { [key in string]: number[] },
};

/**  Result of `store_save_dirty`: bytes written to the delta sidecar (0 = skipped). */
export type SaveResult = {
	savedBytes: number,
};

export type SavedSelection = {
	selector: Selector,
	/**  Tag id -> the name it carried when saved. What makes a map-local `Tag` leaf portable. */
	tagNames: { [key in number]: string },
} & SavedSelectionInfo;

/**
 *  A rule's identity and label, with no tree attached. What the UI lists and holds; the
 *  body is a separate read because a single `Polygon` leaf can carry a country border's
 *  coordinates (~1.7MB of JSON at the heavy border detail).
 */
export type SavedSelectionInfo = {
	id: string,
	name: string,
	color: [number, number, number],
	createdAt: string,
};

/**
 *  Score bounding box: either `"auto"` (computed from locations) or an
 *  explicit `[south, west, north, east]` rectangle.
 */
export type ScoreBounds = string | [number, number, number, number];

/**  A panorama visit record. */
export type SeenEntry = {
	id: number,
	panoId: string,
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	enteredAt: number,
	mapId: string | null,
	locationId: number | null,
	countryCode: string | null,
	address: string | null,
	thumbnail: string | null,
};

/**
 *  Filters for seen-history queries. All fields are AND-combined.
 *  `search` matches against the address.
 */
export type SeenFilter = {
	country?: string | null,
	mapId?: string | null,
	search?: string | null,
};

/**  Map ID and display name for seen-history filtering. */
export type SeenMapInfo = {
	id: string,
	name: string,
};

/**  Parameters for recording a panorama visit. */
export type SeenWriteEntry = {
	panoId: string,
	lat: number,
	lng: number,
	heading: number,
	pitch: number,
	zoom: number,
	enteredAt: number,
	mapId: string | null,
	locationId: number | null,
	countryCode: string | null,
	address: string | null,
	thumbnail: string | null,
};

/**
 *  The selection drawing a row: its colour, and its index in `SelectionState::resolved`.
 *  The index is the draw order - a later selection overdraws an earlier one - so the
 *  overlay can be ordered by it instead of by whatever order rows happen to arrive in.
 *  Every marker sits at z=0 in one deck.gl layer, so buffer order is the only z there is.
 */
export type SelPaint = {
	idx: number,
	color: [number, number, number],
};

/**
 *  A named, colored selection. `key` is deterministic (e.g., `"tag:5"`, `"polygon:abc"`)
 *  so JS can diff selections across syncs. `color` is the RGB overlay color.
 */
export type Selection = {
	key: string,
	color: [number, number, number],
	selector: Selector,
};

/**
 *  A top-level row of `store_sync_selections`: the selection itself, plus whether it is
 *  ghosted. Ghosting means nothing for a nested child, which is why the flag lives here
 *  and not on `Selection`.
 */
export type SelectionInput = {
	/**  Counted, but kept out of the overlay and the selected set. */
	ghosted?: boolean,
} & Selection;

/**
 *  Selection bitmask sync payload. `bitmask` carries the packed per-cell bitmask bytes
 *  inline in the IPC response (no shared temp file → no clobber race under concurrent
 *  mutations). `None` when nothing changed. `counts` gives per-selection match counts.
 */
export type SelectionSync = {
	/**  Resolved count per selection node, keyed by `Selection.key` (top-level and nested). */
	counts: { [key in string]: number },
	bitmask: number[] | null,
	selectedCount: number,
};

/**
 *  Discriminated union of all selection types. Serialized with `{ "type": "..." }` tag
 *  for JS interop. Simple types (Tag, Untagged, PanoIds, etc.) resolve in O(N) with
 *   parallel batch scans. Composites (Intersection, Union, Invert) recursively resolve
 *  children. Duplicates uses a grid-accelerated spatial scan.
 */
export type Selector = { type: "Locations"; locations: number[]; name: string | null } | { type: "Everything" } | { type: "Polygon"; polygon: PolygonGeometry } | { type: "Tag"; tagId: number } | { type: "Untagged" } | { type: "Unpanned" } | { type: "PanoIds" } | { type: "NotPanoIds" } | { type: "Uncommitted" } | { type: "Manual"; locations: number[] } | { type: "Duplicates"; distance: number } | { type: "ValidationState"; locations: number[]; state: number } | { type: "Reviewed"; locations: number[]; sessionId: string; mode: string } | { type: "Intersection"; selections: Selection[] } | { type: "Union"; selections: Selection[] } | { type: "Invert"; selections: Selection[] } | { type: "Filter"; field: string; test: FilterOp } | 
/**
 *  Rank a selection by a `field_expr`, optionally keeping only the first `k`. Emits
 *  a ranked root in rank order, where every other selector answers ascending. With no
 *  `k` this selects its child unchanged and states only how to walk it. A member the
 *  expression cannot score ranks last, so ranking never drops anything.
 */
{ type: "Ranked"; 
/**  What to rank; `None` ranks the whole map. */
selection: Selection | null; expr: string; k: number | null; ascending: boolean };

export type SideCounts = {
	create: number,
	update: number,
	delete: number,
};

export type SidecarDone = {
	reqId: number,
	error: string | null,
};

export type SidecarLine = {
	reqId: number,
	line: string,
};

/**  Same shape as [`SidecarLine`]; distinct so the two event channels can't be cross-wired. */
export type SidecarLog = {
	reqId: number,
	line: string,
};

export type SidecarProgress = {
	pluginId: string,
	downloaded: number,
	total: number,
};

/**
 *  Where a provider's results go. `Patch` applies them to the locations they name;
 *  `Collect` delivers them to the caller and writes nothing. The declaration decides
 *  this, never the contents of a result.
 */
export type Sink = "patch" | "collect";

/**
 *  `pick_spaced`'s answer: the picked ids plus the spacing achieved (count mode) or
 *  enforced (distance mode).
 */
export type SpacedPickResult = {
	ids: number[],
	distanceM: number,
};

/**
 *  Open-time snapshot: the same `values` a mutation result carries, with every field
 *  present. The one full picture JS ever receives; everything after is a delta.
 */
export type StoreStatus = {
	version: number,
	values: EngineValues,
};

/**  User-facing warning toast. */
export type StoreWarning = string;

/**  Lightweight status for polling: count, version, and whether unsaved changes exist. */
export type SummaryResult = {
	locationCount: number,
	version: number,
	dirtyCount: number,
};

/**
 *  Only the fields a pull genuinely changes. A field the provider cannot represent reads as empty
 *  on the remote side and must not overwrite local data, so absent fields are left untouched.
 *  `pano_id` applies only when `pano_id_set` is true (a cleared panoId is a real change to `null`).
 */
export type SyncPatch = {
	lat: number | null,
	lng: number | null,
	heading: number | null,
	pitch: number | null,
	zoom: number | null,
	panoIdSet: boolean,
	panoId: string | null,
	flags: number | null,
	tags: string[] | null,
};

/**  Everything the reconcile settled to, for the JS side. Every array is empty on an unchanged map. */
export type SyncReconcileResult = {
	/**  Remote-applied counts; mirror-from-local deletes fold into `delete`. */
	pushed: SideCounts,
	/**  Local-applied counts; mirror-from-remote deletes fold into `delete`. */
	pulled: SideCounts,
	adopted: number,
	conflicts: Conflict[],
	neededTags: string[],
	pullCreates: PullCreate[],
	pullUpdates: PullUpdate[],
	pullDeleteIds: number[],
	mirrorLocalDeleteIds: number[],
};

export type Tag = {
	id: number,
	name: string,
	/**
	 *  Hex color string (e.g. "#3a7fc2"). Generated deterministically from
	 *  the tag name via `util::color_for_name` when not explicitly set.
	 */
	color: string,
	visible?: boolean,
	/**
	 *  Display order in the sidebar tag list. `None` for legacy tags
	 *  that predate ordered insertion.
	 */
	order: number | null,
	/**
	 *  Document links from the map JSON's `extra.tags[name].doclinks` --
	 *  URLs into external docs (e.g. Google Docs heading links). Read-only
	 *  in the app; round-trips through import/export.
	 */
	doclinks?: string[],
};

/**  Patchable fields of a `Tag`. Subset by design: id/visible aren't editable here. */
export type TagPatch = {
	name?: string | null,
	color?: string | null,
	/**  Full replacement for the tag's doclink URLs (empty vec clears). */
	doclinks?: string[] | null,
};

/**
 *  Generic `{id, patch}` update envelope, parameterized by the patch type. Specta
 *  has no `Partial<T>`, and a patch is a deliberate *subset* of patchable fields, so
 *  each entity names its own patch struct (e.g. `TagPatch`) rather than deriving one.
 */
export type Update<P> = {
	id: number,
	patch: P,
};

export type UpdateAvailable = {
	version: string,
	currentVersion: string,
	notes: string | null,
};

/**  Download progress, emitted per chunk. `total` is absent when the server sends no length. */
export type UpdateProgress = {
	downloaded: number,
	total: number | null,
};

/**  How far behind one country's downloaded coverage data is. */
export type ValiCountryStatus = {
	countryCode: string,
	files: number,
	bytes: number,
};

export type ValiLocation_Deserialize = {
	lat: number,
	lng: number,
	heading: number,
	zoom: number | null,
	pitch: number | null,
	panoId: string | null,
	tags: string[],
};

export type ValiLocation = {
	lat: number,
	lng: number,
	heading: number,
	zoom?: number | null,
	pitch?: number | null,
	panoId?: string | null,
	tags: string[],
};

export type ValiProgress = { kind: "workItems"; total: number } | { kind: "workItemDone"; countryCode: string; subdivisionCode: string | null; done: number; total: number } | { kind: "countryDownloadStarted"; countryCode: string; files: number; bytes: number; updates: boolean } | { kind: "fileDownloaded"; countryCode: string; name: string; bytes: number };

/**
 *  Per-map config for a virtual tag-tree node - a folder node with no underlying
 *  tag (e.g. "a" when only "a/b" and "a/c" exist). Keyed by the node's full slash
 *  path in `MapSettings::virtual_tags`. Tree-view only; never creates a real tag.
 */
export type VirtualTag = {
	color?: string | null,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: T) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

