// Generated by `npm run gen:bindings`. Do not edit.
// No imports, ever: procedures bundle this file and must not reach Tauri.

/** Per-location bitfield, serialized as a plain `u32` over IPC and Arrow. */
export const LocationFlag = {
	None: 0,
	LoadAsPanoId: 1,
	Informational: 2,
	ImportPreview: 4,
	SeenOverlay: 8,
} as const;
export type LocationFlag = (typeof LocationFlag)[keyof typeof LocationFlag];

/** Panorama source type, as Google's metadata reports it. */
export const PanoType = { Official: 2, Unknown: 3, UserUploaded: 10 } as const;
export type PanoType = (typeof PanoType)[keyof typeof PanoType];

/** Outcome of a Street View coverage check, as `validate` answers it per row. */
export const ValidationState = {
	Ok: 0,
	UpdateAvailable: 1,
	UpdateApplied: 2,
	GoodcamAvailable: 6,
	PanoIdBroke: 4,
	Unofficial: 5,
	NotFound: 3,
} as const;
export type ValidationState = (typeof ValidationState)[keyof typeof ValidationState];

/** The bits a preview carries that a real location must not. */
export const VIRTUAL_FLAGS = 12 as const;
