// code generated by pbf v5.1.0

export function readNodeKey(pbf, end) {
    const obj = {path: "", epoch: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.path = pbf.readString();
        else if (field === 2) obj.epoch = pbf.readVarint();
    }
    return obj;
}
export function writeNodeKey(obj, pbf) {
    if (obj.path) pbf.writeStringField(1, obj.path);
    if (obj.epoch) pbf.writeVarintField(2, obj.epoch);
}

export function readBulkMetadata(pbf, end) {
    const obj = {node_metadata: [], head_node_key: undefined, head_node_center: [], meters_per_texel: [], default_imagery_epoch: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.node_metadata.push(readNodeMetadata(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 2) obj.head_node_key = readNodeKey(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 3) pbf.readPackedDouble(obj.head_node_center);
        else if (field === 4) pbf.readPackedFloat(obj.meters_per_texel);
        else if (field === 5) obj.default_imagery_epoch = pbf.readVarint();
    }
    return obj;
}
export function writeBulkMetadata(obj, pbf) {
    if (obj.node_metadata) for (const item of obj.node_metadata) pbf.writeMessage(1, writeNodeMetadata, item);
    if (obj.head_node_key) pbf.writeMessage(2, writeNodeKey, obj.head_node_key);
    if (obj.head_node_center) pbf.writePackedDouble(3, obj.head_node_center);
    if (obj.meters_per_texel) pbf.writePackedFloat(4, obj.meters_per_texel);
    if (obj.default_imagery_epoch) pbf.writeVarintField(5, obj.default_imagery_epoch);
}

export function readNodeMetadata(pbf, end) {
    const obj = {path_and_flags: 0, epoch: 0, oriented_bounding_box: undefined, meters_per_texel: 0, bulk_metadata_epoch: 0, imagery_epoch: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.path_and_flags = pbf.readVarint();
        else if (field === 2) obj.epoch = pbf.readVarint();
        else if (field === 3) obj.oriented_bounding_box = pbf.readBytes();
        else if (field === 4) obj.meters_per_texel = pbf.readFloat();
        else if (field === 5) obj.bulk_metadata_epoch = pbf.readVarint();
        else if (field === 7) obj.imagery_epoch = pbf.readVarint();
    }
    return obj;
}
export function writeNodeMetadata(obj, pbf) {
    if (obj.path_and_flags) pbf.writeVarintField(1, obj.path_and_flags);
    if (obj.epoch) pbf.writeVarintField(2, obj.epoch);
    if (obj.oriented_bounding_box != null) pbf.writeBytesField(3, obj.oriented_bounding_box);
    if (obj.meters_per_texel) pbf.writeFloatField(4, obj.meters_per_texel);
    if (obj.bulk_metadata_epoch) pbf.writeVarintField(5, obj.bulk_metadata_epoch);
    if (obj.imagery_epoch) pbf.writeVarintField(7, obj.imagery_epoch);
}

export const NodeMetadataFlags = {
    "RICH3D_LEAF": 1,
    "RICH3D_NODATA": 2,
    "LEAF": 4,
    "NODATA": 8,
    "USE_IMAGERY_EPOCH": 16
};

export function readNodeData(pbf, end) {
    const obj = {matrix_globe_from_mesh: [], meshes: [], for_normals: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) pbf.readPackedDouble(obj.matrix_globe_from_mesh);
        else if (field === 2) obj.meshes.push(readMesh(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 8) obj.for_normals = pbf.readBytes();
    }
    return obj;
}
export function writeNodeData(obj, pbf) {
    if (obj.matrix_globe_from_mesh) pbf.writePackedDouble(1, obj.matrix_globe_from_mesh);
    if (obj.meshes) for (const item of obj.meshes) pbf.writeMessage(2, writeMesh, item);
    if (obj.for_normals != null) pbf.writeBytesField(8, obj.for_normals);
}

export function readMesh(pbf, end) {
    const obj = {vertices: undefined, texture_coords: undefined, indices: undefined, texture: [], texture_coordinates: undefined, layer_and_octant_counts: undefined, uv_offset_and_scale: [], normals: undefined, mesh_id: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.vertices = pbf.readBytes();
        else if (field === 2) obj.texture_coords = pbf.readBytes();
        else if (field === 3) obj.indices = pbf.readBytes();
        else if (field === 6) obj.texture.push(readTexture(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 7) obj.texture_coordinates = pbf.readBytes();
        else if (field === 8) obj.layer_and_octant_counts = pbf.readBytes();
        else if (field === 10) pbf.readPackedFloat(obj.uv_offset_and_scale);
        else if (field === 11) obj.normals = pbf.readBytes();
        else if (field === 12) obj.mesh_id = pbf.readVarint();
    }
    return obj;
}
export function writeMesh(obj, pbf) {
    if (obj.vertices != null) pbf.writeBytesField(1, obj.vertices);
    if (obj.texture_coords != null) pbf.writeBytesField(2, obj.texture_coords);
    if (obj.indices != null) pbf.writeBytesField(3, obj.indices);
    if (obj.texture) for (const item of obj.texture) pbf.writeMessage(6, writeTexture, item);
    if (obj.texture_coordinates != null) pbf.writeBytesField(7, obj.texture_coordinates);
    if (obj.layer_and_octant_counts != null) pbf.writeBytesField(8, obj.layer_and_octant_counts);
    if (obj.uv_offset_and_scale) pbf.writePackedFloat(10, obj.uv_offset_and_scale);
    if (obj.normals != null) pbf.writeBytesField(11, obj.normals);
    if (obj.mesh_id) pbf.writeVarintField(12, obj.mesh_id);
}

export function readTexture(pbf, end) {
    const obj = {data: [], format: 0, width: 256, height: 256};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.data.push(pbf.readBytes());
        else if (field === 2) obj.format = pbf.readVarint();
        else if (field === 3) obj.width = pbf.readVarint();
        else if (field === 4) obj.height = pbf.readVarint();
    }
    return obj;
}
export function writeTexture(obj, pbf) {
    if (obj.data) for (const item of obj.data) pbf.writeBytesField(1, item);
    if (obj.format) pbf.writeVarintField(2, obj.format);
    if (obj.width != null && obj.width !== 256) pbf.writeVarintField(3, obj.width);
    if (obj.height != null && obj.height !== 256) pbf.writeVarintField(4, obj.height);
}

export const TextureFormat = {
    "JPG": 1,
    "DXT1": 2,
    "ETC1": 3,
    "PVRTC2": 4,
    "PVRTC4": 5,
    "CRN_DXT1": 6
};

export function readPlanetoidMetadata(pbf, end) {
    const obj = {root_node_metadata: undefined, radius: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.root_node_metadata = readNodeMetadata(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.radius = pbf.readFloat();
    }
    return obj;
}
export function writePlanetoidMetadata(obj, pbf) {
    if (obj.root_node_metadata) pbf.writeMessage(1, writeNodeMetadata, obj.root_node_metadata);
    if (obj.radius) pbf.writeFloatField(2, obj.radius);
}
