//! DST-correct UTC offsets from a packed transition table read in place -- the
//! replacement for linking `chrono-tz`'s full database. `data/tz.bin` holds, per IANA
//! zone name, the total offset (utc + dst) at every transition instant in the u32 Unix
//! range; aliased zones share one transition run. Regenerated by the `regenerate_table`
//! test in `lib.test.rs`, which uses `chrono-tz` as the source and oracle.

use std::str::from_utf8;

const HEADER_LEN: usize = 32;
const ENTRY: usize = 12;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    BadMagic,
    UnsupportedVersion(u32),
    Truncated,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::BadMagic => write!(f, "not a packed tz table"),
            Error::UnsupportedVersion(v) => write!(f, "unsupported tz table version {v}"),
            Error::Truncated => write!(f, "tz table shorter than its header claims"),
        }
    }
}

impl std::error::Error for Error {}

pub struct Tz<'a> {
    data: &'a [u8],
    zone_count: usize,
    names_idx_at: usize,
    trans_idx_at: usize,
    names_at: usize,
    trans_at: usize,
}

impl<'a> Tz<'a> {
    pub fn new(data: &'a [u8]) -> Result<Self, Error> {
        if data.len() < HEADER_LEN {
            return Err(Error::Truncated);
        }
        let u32_at = |off: usize| u32::from_le_bytes(data[off..off + 4].try_into().unwrap());
        if &data[0..4] != b"MMTZ" {
            return Err(Error::BadMagic);
        }
        let version = u32_at(4);
        if version != 1 {
            return Err(Error::UnsupportedVersion(version));
        }
        let zone_count = u32_at(8) as usize;
        let t = Tz {
            data,
            zone_count,
            names_idx_at: u32_at(12) as usize,
            trans_idx_at: u32_at(16) as usize,
            names_at: u32_at(20) as usize,
            trans_at: u32_at(24) as usize,
        };
        let idx_end = t.trans_idx_at + zone_count * 8;
        if data.len() < idx_end || t.names_idx_at + (zone_count + 1) * 4 > data.len() {
            return Err(Error::Truncated);
        }
        Ok(t)
    }

    pub fn zone_count(&self) -> usize {
        self.zone_count
    }

    fn u32_at(&self, off: usize) -> u32 {
        u32::from_le_bytes(self.data[off..off + 4].try_into().unwrap())
    }

    pub fn zone_name(&self, i: usize) -> &'a str {
        let a = self.u32_at(self.names_idx_at + i * 4) as usize;
        let b = self.u32_at(self.names_idx_at + i * 4 + 4) as usize;
        from_utf8(&self.data[self.names_at + a..self.names_at + b]).unwrap_or_default()
    }

    /// Index of `name` among the lexicographically sorted zone names.
    pub fn zone_index(&self, name: &str) -> Option<usize> {
        let mut lo = 0usize;
        let mut hi = self.zone_count;
        while lo < hi {
            let mid = (lo + hi) / 2;
            match self.zone_name(mid).cmp(name) {
                std::cmp::Ordering::Less => lo = mid + 1,
                std::cmp::Ordering::Greater => hi = mid,
                std::cmp::Ordering::Equal => return Some(mid),
            }
        }
        None
    }

    /// Total UTC offset (utc + dst) in seconds for the zone at instant `ts`.
    pub fn offset_at(&self, zone: usize, ts: i64) -> i32 {
        let a = self.u32_at(self.trans_idx_at + zone * 8) as usize;
        let b = self.u32_at(self.trans_idx_at + zone * 8 + 4) as usize;
        // Last entry with entry.ts <= ts; the first entry of every zone is i64::MIN.
        let (mut lo, mut hi) = (a, b);
        while hi - lo > 1 {
            let mid = (lo + hi) / 2;
            let at = self.trans_at + mid * ENTRY;
            let t = i64::from_le_bytes(self.data[at..at + 8].try_into().unwrap());
            if t <= ts {
                lo = mid;
            } else {
                hi = mid;
            }
        }
        let at = self.trans_at + lo * ENTRY;
        i32::from_le_bytes(self.data[at + 8..at + 12].try_into().unwrap())
    }

    /// [`Self::zone_index`] + [`Self::offset_at`]; `None` for an unknown zone name.
    pub fn offset_seconds(&self, name: &str, ts: i64) -> Option<i32> {
        Some(self.offset_at(self.zone_index(name)?, ts))
    }
}

#[cfg(test)]
#[path = "lib.test.rs"]
mod tests;
