// code generated by pbf v5.1.0

export function readGetMetadataRequest(pbf, end) {
    const obj = {context: undefined, locale: undefined, key: [], spec: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.context = readRequestContext(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.locale = readLocalizationContext(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 3) obj.key.push(readKeyWrapper(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 4) obj.spec = readMetadataResponseSpecification(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writeGetMetadataRequest(obj, pbf) {
    if (obj.context) pbf.writeMessage(1, writeRequestContext, obj.context);
    if (obj.locale) pbf.writeMessage(2, writeLocalizationContext, obj.locale);
    if (obj.key) for (const item of obj.key) pbf.writeMessage(3, writeKeyWrapper, item);
    if (obj.spec) pbf.writeMessage(4, writeMetadataResponseSpecification, obj.spec);
}

export function readRequestContext(pbf, end) {
    const obj = {productId: "", language: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.productId = pbf.readString();
        else if (field === 5) obj.language = pbf.readString();
    }
    return obj;
}
export function writeRequestContext(obj, pbf) {
    if (obj.productId) pbf.writeStringField(1, obj.productId);
    if (obj.language) pbf.writeStringField(5, obj.language);
}

export function readLocalizationContext(pbf, end) {
    const obj = {language: "", regionCode: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.language = pbf.readString();
        else if (field === 2) obj.regionCode = pbf.readString();
    }
    return obj;
}
export function writeLocalizationContext(obj, pbf) {
    if (obj.language) pbf.writeStringField(1, obj.language);
    if (obj.regionCode) pbf.writeStringField(2, obj.regionCode);
}

export function readKeyWrapper(pbf, end) {
    const obj = {key: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.key = readImageKey(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writeKeyWrapper(obj, pbf) {
    if (obj.key) pbf.writeMessage(1, writeImageKey, obj.key);
}

export function readMetadataResponseSpecification(pbf, end) {
    const obj = {component: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) pbf.readPackedVarint(obj.component, true);
    }
    return obj;
}
export function writeMetadataResponseSpecification(obj, pbf) {
    if (obj.component) for (const item of obj.component) pbf.writeVarintField(1, item);
}

export function readGetMetadataResponse(pbf, end) {
    const obj = {status: undefined, metadata: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.status = readResponseStatus(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.metadata.push(readImageMetadata(pbf, pbf.readVarint() + pbf.pos));
    }
    return obj;
}
export function writeGetMetadataResponse(obj, pbf) {
    if (obj.status) pbf.writeMessage(1, writeResponseStatus, obj.status);
    if (obj.metadata) for (const item of obj.metadata) pbf.writeMessage(2, writeImageMetadata, item);
}

export function readResponseStatus(pbf, end) {
    const obj = {code: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.code = pbf.readVarint(true);
    }
    return obj;
}
export function writeResponseStatus(obj, pbf) {
    if (obj.code) pbf.writeVarintField(1, obj.code);
}

export function readImageMetadata(pbf, end) {
    const obj = {status: undefined, pano: undefined, tiles: undefined, description: undefined, attribution: undefined, information: [], date: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.status = readImageStatus(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.pano = readImageKey(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 3) obj.tiles = readImageTiles(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 4) obj.description = readImageDescription(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 5) obj.attribution = readImageAttribution(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 6) obj.information.push(readImageInformation(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 7) obj.date = readImageDate(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writeImageMetadata(obj, pbf) {
    if (obj.status) pbf.writeMessage(1, writeImageStatus, obj.status);
    if (obj.pano) pbf.writeMessage(2, writeImageKey, obj.pano);
    if (obj.tiles) pbf.writeMessage(3, writeImageTiles, obj.tiles);
    if (obj.description) pbf.writeMessage(4, writeImageDescription, obj.description);
    if (obj.attribution) pbf.writeMessage(5, writeImageAttribution, obj.attribution);
    if (obj.information) for (const item of obj.information) pbf.writeMessage(6, writeImageInformation, item);
    if (obj.date) pbf.writeMessage(7, writeImageDate, obj.date);
}

export function readImageStatus(pbf, end) {
    const obj = {code: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.code = pbf.readVarint(true);
    }
    return obj;
}
export function writeImageStatus(obj, pbf) {
    if (obj.code) pbf.writeVarintField(1, obj.code);
}

export function readImageKey(pbf, end) {
    const obj = {frontend: 0, id: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.frontend = pbf.readVarint(true);
        else if (field === 2) obj.id = pbf.readString();
    }
    return obj;
}
export function writeImageKey(obj, pbf) {
    if (obj.frontend) pbf.writeVarintField(1, obj.frontend);
    if (obj.id) pbf.writeStringField(2, obj.id);
}

export function readImageSize(pbf, end) {
    const obj = {height: 0, width: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.height = pbf.readVarint(true);
        else if (field === 2) obj.width = pbf.readVarint(true);
    }
    return obj;
}
export function writeImageSize(obj, pbf) {
    if (obj.height) pbf.writeVarintField(1, obj.height);
    if (obj.width) pbf.writeVarintField(2, obj.width);
}

export function readImageTiles(pbf, end) {
    const obj = {worldSize: undefined, tileSize: undefined, panoId: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 3) obj.worldSize = readImageSize(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 4) obj.tileSize = readImageTileSize(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 10) obj.panoId = pbf.readString();
    }
    return obj;
}
export function writeImageTiles(obj, pbf) {
    if (obj.worldSize) pbf.writeMessage(3, writeImageSize, obj.worldSize);
    if (obj.tileSize) pbf.writeMessage(4, writeImageTileSize, obj.tileSize);
    if (obj.panoId) pbf.writeStringField(10, obj.panoId);
}

export function readImageTileSize(pbf, end) {
    const obj = {possible: [], tileSize: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.possible.push(readPossibleSize(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 2) obj.tileSize = readImageSize(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writeImageTileSize(obj, pbf) {
    if (obj.possible) for (const item of obj.possible) pbf.writeMessage(1, writePossibleSize, item);
    if (obj.tileSize) pbf.writeMessage(2, writeImageSize, obj.tileSize);
}

export function readPossibleSize(pbf, end) {
    const obj = {size: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.size = readImageSize(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writePossibleSize(obj, pbf) {
    if (obj.size) pbf.writeMessage(1, writeImageSize, obj.size);
}

export function readLocalizedText(pbf, end) {
    const obj = {text: "", language: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.text = pbf.readString();
        else if (field === 2) obj.language = pbf.readString();
    }
    return obj;
}
export function writeLocalizedText(obj, pbf) {
    if (obj.text) pbf.writeStringField(1, obj.text);
    if (obj.language) pbf.writeStringField(2, obj.language);
}

export function readImageDescription(pbf, end) {
    const obj = {description: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 3) obj.description.push(readLocalizedText(pbf, pbf.readVarint() + pbf.pos));
    }
    return obj;
}
export function writeImageDescription(obj, pbf) {
    if (obj.description) for (const item of obj.description) pbf.writeMessage(3, writeLocalizedText, item);
}

export function readImageTitle(pbf, end) {
    const obj = {name: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.name = pbf.readString();
    }
    return obj;
}
export function writeImageTitle(obj, pbf) {
    if (obj.name) pbf.writeStringField(1, obj.name);
}

export function readAttributionItem(pbf, end) {
    const obj = {name: undefined, url: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.name = readImageTitle(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.url = pbf.readString();
    }
    return obj;
}
export function writeAttributionItem(obj, pbf) {
    if (obj.name) pbf.writeMessage(1, writeImageTitle, obj.name);
    if (obj.url) pbf.writeStringField(2, obj.url);
}

export function readImageAuthor(pbf, end) {
    const obj = {name: undefined, profileUrl: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.name = readLocalizedText(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.profileUrl = pbf.readString();
    }
    return obj;
}
export function writeImageAuthor(obj, pbf) {
    if (obj.name) pbf.writeMessage(1, writeLocalizedText, obj.name);
    if (obj.profileUrl) pbf.writeStringField(2, obj.profileUrl);
}

export function readImageAttribution(pbf, end) {
    const obj = {item: [], author: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.item.push(readAttributionItem(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 2) obj.author.push(readImageAuthor(pbf, pbf.readVarint() + pbf.pos));
    }
    return obj;
}
export function writeImageAttribution(obj, pbf) {
    if (obj.item) for (const item of obj.item) pbf.writeMessage(1, writeAttributionItem, item);
    if (obj.author) for (const item of obj.author) pbf.writeMessage(2, writeImageAuthor, item);
}

export function readLatLng(pbf, end) {
    const obj = {lat: 0, lng: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 3) obj.lat = pbf.readDouble();
        else if (field === 4) obj.lng = pbf.readDouble();
    }
    return obj;
}
export function writeLatLng(obj, pbf) {
    if (obj.lat) pbf.writeDoubleField(3, obj.lat);
    if (obj.lng) pbf.writeDoubleField(4, obj.lng);
}

export function readAltitude(pbf, end) {
    const obj = {meters: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.meters = pbf.readFloat();
    }
    return obj;
}
export function writeAltitude(obj, pbf) {
    if (obj.meters) pbf.writeFloatField(1, obj.meters);
}

export function readPov(pbf, end) {
    const obj = {heading: 0, tilt: 0, roll: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.heading = pbf.readFloat();
        else if (field === 2) obj.tilt = pbf.readFloat();
        else if (field === 3) obj.roll = pbf.readFloat();
    }
    return obj;
}
export function writePov(obj, pbf) {
    if (obj.heading) pbf.writeFloatField(1, obj.heading);
    if (obj.tilt) pbf.writeFloatField(2, obj.tilt);
    if (obj.roll) pbf.writeFloatField(3, obj.roll);
}

export function readLevel(pbf, end) {
    const obj = {id: 0, name: undefined, abbreviation: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.id = pbf.readVarint();
        else if (field === 3) obj.name = readLocalizedText(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 4) obj.abbreviation = readLocalizedText(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writeLevel(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.name) pbf.writeMessage(3, writeLocalizedText, obj.name);
    if (obj.abbreviation) pbf.writeMessage(4, writeLocalizedText, obj.abbreviation);
}

export function readPanoLocation(pbf, end) {
    const obj = {location: undefined, altitude: undefined, pov: undefined, level: undefined, countryCode: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.location = readLatLng(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.altitude = readAltitude(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 3) obj.pov = readPov(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 4) obj.level = readLevel(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 5) obj.countryCode = pbf.readString();
    }
    return obj;
}
export function writePanoLocation(obj, pbf) {
    if (obj.location) pbf.writeMessage(1, writeLatLng, obj.location);
    if (obj.altitude) pbf.writeMessage(2, writeAltitude, obj.altitude);
    if (obj.pov) pbf.writeMessage(3, writePov, obj.pov);
    if (obj.level) pbf.writeMessage(4, writeLevel, obj.level);
    if (obj.countryCode) pbf.writeStringField(5, obj.countryCode);
}

export function readPano(pbf, end) {
    const obj = {key: undefined, location: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.key = readImageKey(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 3) obj.location = readPanoLocation(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writePano(obj, pbf) {
    if (obj.key) pbf.writeMessage(1, writeImageKey, obj.key);
    if (obj.location) pbf.writeMessage(3, writePanoLocation, obj.location);
}

export function readPanoRelations(pbf, end) {
    const obj = {pano: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.pano.push(readPano(pbf, pbf.readVarint() + pbf.pos));
    }
    return obj;
}
export function writePanoRelations(obj, pbf) {
    if (obj.pano) for (const item of obj.pano) pbf.writeMessage(1, writePano, item);
}

export function readPanoLinkProperties(pbf, end) {
    const obj = {heading: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 4) obj.heading = pbf.readFloat();
    }
    return obj;
}
export function writePanoLinkProperties(obj, pbf) {
    if (obj.heading) pbf.writeFloatField(4, obj.heading);
}

export function readPanoLink(pbf, end) {
    const obj = {target: 0, properties: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.target = pbf.readVarint(true);
        else if (field === 2) obj.properties = readPanoLinkProperties(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writePanoLink(obj, pbf) {
    if (obj.target) pbf.writeVarintField(1, obj.target);
    if (obj.properties) pbf.writeMessage(2, writePanoLinkProperties, obj.properties);
}

export function readPanoDate(pbf, end) {
    const obj = {year: 0, month: 0, day: 0};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.year = pbf.readVarint(true);
        else if (field === 2) obj.month = pbf.readVarint(true);
        else if (field === 3) obj.day = pbf.readVarint(true);
    }
    return obj;
}
export function writePanoDate(obj, pbf) {
    if (obj.year) pbf.writeVarintField(1, obj.year);
    if (obj.month) pbf.writeVarintField(2, obj.month);
    if (obj.day) pbf.writeVarintField(3, obj.day);
}

export function readPanoTime(pbf, end) {
    const obj = {target: 0, date: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.target = pbf.readVarint(true);
        else if (field === 2) obj.date = readPanoDate(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writePanoTime(obj, pbf) {
    if (obj.target) pbf.writeVarintField(1, obj.target);
    if (obj.date) pbf.writeMessage(2, writePanoDate, obj.date);
}

export function readImageInformation(pbf, end) {
    const obj = {status: undefined, location: undefined, relations: undefined, link: [], time: []};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 1) obj.status = readImageStatus(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 2) obj.location = readPanoLocation(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 4) obj.relations = readPanoRelations(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 7) obj.link.push(readPanoLink(pbf, pbf.readVarint() + pbf.pos));
        else if (field === 9) obj.time.push(readPanoTime(pbf, pbf.readVarint() + pbf.pos));
    }
    return obj;
}
export function writeImageInformation(obj, pbf) {
    if (obj.status) pbf.writeMessage(1, writeImageStatus, obj.status);
    if (obj.location) pbf.writeMessage(2, writePanoLocation, obj.location);
    if (obj.relations) pbf.writeMessage(4, writePanoRelations, obj.relations);
    if (obj.link) for (const item of obj.link) pbf.writeMessage(7, writePanoLink, item);
    if (obj.time) for (const item of obj.time) pbf.writeMessage(9, writePanoTime, item);
}

export function readDateSourceInfo(pbf, end) {
    const obj = {source: ""};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 3) obj.source = pbf.readString();
    }
    return obj;
}
export function writeDateSourceInfo(obj, pbf) {
    if (obj.source) pbf.writeStringField(3, obj.source);
}

export function readImageDate(pbf, end) {
    const obj = {sourceInfo: undefined, date: undefined};
    let field;
    while ((field = pbf.nextField(end))) {
        if (field === 6) obj.sourceInfo = readDateSourceInfo(pbf, pbf.readVarint() + pbf.pos);
        else if (field === 8) obj.date = readPanoDate(pbf, pbf.readVarint() + pbf.pos);
    }
    return obj;
}
export function writeImageDate(obj, pbf) {
    if (obj.sourceInfo) pbf.writeMessage(6, writeDateSourceInfo, obj.sourceInfo);
    if (obj.date) pbf.writeMessage(8, writePanoDate, obj.date);
}
