// code generated by scripts/gen-proto-array.mjs from getmetadata.proto
// The message shapes, plus readers for their array-JSON ("json+protobuf") form, in which
// index i holds field i+1. Do not edit.

export interface GetMetadataRequest {
	context: RequestContext | undefined;
	locale: LocalizationContext | undefined;
	key: KeyWrapper[];
	spec: MetadataResponseSpecification | undefined;
}

export interface RequestContext {
	productId: string;
	language: string;
}

export interface LocalizationContext {
	language: string;
	regionCode: string;
}

export interface KeyWrapper {
	key: ImageKey | undefined;
}

export interface MetadataResponseSpecification {
	component: number[];
}

export interface GetMetadataResponse {
	status: ResponseStatus | undefined;
	metadata: ImageMetadata[];
}

export interface ResponseStatus {
	code: number;
}

export interface ImageMetadata {
	status: ImageStatus | undefined;
	pano: ImageKey | undefined;
	tiles: ImageTiles | undefined;
	description: ImageDescription | undefined;
	attribution: ImageAttribution | undefined;
	information: ImageInformation[];
	date: ImageDate | undefined;
}

export interface ImageStatus {
	code: number;
}

export interface ImageKey {
	frontend: number;
	id: string;
}

export interface ImageSize {
	height: number;
	width: number;
}

export interface ImageTiles {
	worldSize: ImageSize | undefined;
	tileSize: ImageTileSize | undefined;
	panoId: string;
}

export interface ImageTileSize {
	possible: PossibleSize[];
	tileSize: ImageSize | undefined;
}

export interface PossibleSize {
	size: ImageSize | undefined;
}

export interface LocalizedText {
	text: string;
	language: string;
}

export interface ImageDescription {
	description: LocalizedText[];
}

export interface ImageTitle {
	name: string;
}

export interface AttributionItem {
	name: ImageTitle | undefined;
	url: string;
}

export interface ImageAuthor {
	name: LocalizedText | undefined;
	profileUrl: string;
}

export interface ImageAttribution {
	item: AttributionItem[];
	author: ImageAuthor[];
}

export interface LatLng {
	lat: number;
	lng: number;
}

export interface Altitude {
	meters: number;
}

export interface Pov {
	heading: number;
	tilt: number;
	roll: number;
}

export interface Level {
	id: number;
	name: LocalizedText | undefined;
	abbreviation: LocalizedText | undefined;
}

export interface PanoLocation {
	location: LatLng | undefined;
	altitude: Altitude | undefined;
	pov: Pov | undefined;
	level: Level | undefined;
	countryCode: string;
}

export interface Pano {
	key: ImageKey | undefined;
	location: PanoLocation | undefined;
}

export interface PanoRelations {
	pano: Pano[];
}

export interface PanoLinkProperties {
	heading: number;
}

export interface PanoLink {
	target: number;
	properties: PanoLinkProperties | undefined;
}

export interface PanoDate {
	year: number;
	month: number;
	day: number;
}

export interface PanoTime {
	target: number;
	date: PanoDate | undefined;
}

export interface ImageInformation {
	status: ImageStatus | undefined;
	location: PanoLocation | undefined;
	relations: PanoRelations | undefined;
	link: PanoLink[];
	time: PanoTime[];
}

export interface DateSourceInfo {
	source: string;
}

export interface ImageDate {
	sourceInfo: DateSourceInfo | undefined;
	date: PanoDate | undefined;
}

const list = (v: unknown): unknown[] => (Array.isArray(v) ? v : []);
const msg = (v: unknown): unknown[] | undefined => (Array.isArray(v) ? v : undefined);
const num = (v: unknown): number => (typeof v === "number" ? v : 0);
const str = (v: unknown): string => (typeof v === "string" ? v : "");

export function readGetMetadataRequest(v: unknown): GetMetadataRequest {
	const a = list(v);
	return {
		context: msg(a[0]) && readRequestContext(a[0]),
		locale: msg(a[1]) && readLocalizationContext(a[1]),
		key: list(a[2]).map((e) => readKeyWrapper(e)),
		spec: msg(a[3]) && readMetadataResponseSpecification(a[3]),
	};
}

export function readRequestContext(v: unknown): RequestContext {
	const a = list(v);
	return {
		productId: str(a[0]),
		language: str(a[4]),
	};
}

export function readLocalizationContext(v: unknown): LocalizationContext {
	const a = list(v);
	return {
		language: str(a[0]),
		regionCode: str(a[1]),
	};
}

export function readKeyWrapper(v: unknown): KeyWrapper {
	const a = list(v);
	return {
		key: msg(a[0]) && readImageKey(a[0]),
	};
}

export function readMetadataResponseSpecification(v: unknown): MetadataResponseSpecification {
	const a = list(v);
	return {
		component: list(a[0]).map((e) => num(e)),
	};
}

export function readGetMetadataResponse(v: unknown): GetMetadataResponse {
	const a = list(v);
	return {
		status: msg(a[0]) && readResponseStatus(a[0]),
		metadata: list(a[1]).map((e) => readImageMetadata(e)),
	};
}

export function readResponseStatus(v: unknown): ResponseStatus {
	const a = list(v);
	return {
		code: num(a[0]),
	};
}

export function readImageMetadata(v: unknown): ImageMetadata {
	const a = list(v);
	return {
		status: msg(a[0]) && readImageStatus(a[0]),
		pano: msg(a[1]) && readImageKey(a[1]),
		tiles: msg(a[2]) && readImageTiles(a[2]),
		description: msg(a[3]) && readImageDescription(a[3]),
		attribution: msg(a[4]) && readImageAttribution(a[4]),
		information: list(a[5]).map((e) => readImageInformation(e)),
		date: msg(a[6]) && readImageDate(a[6]),
	};
}

export function readImageStatus(v: unknown): ImageStatus {
	const a = list(v);
	return {
		code: num(a[0]),
	};
}

export function readImageKey(v: unknown): ImageKey {
	const a = list(v);
	return {
		frontend: num(a[0]),
		id: str(a[1]),
	};
}

export function readImageSize(v: unknown): ImageSize {
	const a = list(v);
	return {
		height: num(a[0]),
		width: num(a[1]),
	};
}

export function readImageTiles(v: unknown): ImageTiles {
	const a = list(v);
	return {
		worldSize: msg(a[2]) && readImageSize(a[2]),
		tileSize: msg(a[3]) && readImageTileSize(a[3]),
		panoId: str(a[9]),
	};
}

export function readImageTileSize(v: unknown): ImageTileSize {
	const a = list(v);
	return {
		possible: list(a[0]).map((e) => readPossibleSize(e)),
		tileSize: msg(a[1]) && readImageSize(a[1]),
	};
}

export function readPossibleSize(v: unknown): PossibleSize {
	const a = list(v);
	return {
		size: msg(a[0]) && readImageSize(a[0]),
	};
}

export function readLocalizedText(v: unknown): LocalizedText {
	const a = list(v);
	return {
		text: str(a[0]),
		language: str(a[1]),
	};
}

export function readImageDescription(v: unknown): ImageDescription {
	const a = list(v);
	return {
		description: list(a[2]).map((e) => readLocalizedText(e)),
	};
}

export function readImageTitle(v: unknown): ImageTitle {
	const a = list(v);
	return {
		name: str(a[0]),
	};
}

export function readAttributionItem(v: unknown): AttributionItem {
	const a = list(v);
	return {
		name: msg(a[0]) && readImageTitle(a[0]),
		url: str(a[1]),
	};
}

export function readImageAuthor(v: unknown): ImageAuthor {
	const a = list(v);
	return {
		name: msg(a[0]) && readLocalizedText(a[0]),
		profileUrl: str(a[1]),
	};
}

export function readImageAttribution(v: unknown): ImageAttribution {
	const a = list(v);
	return {
		item: list(a[0]).map((e) => readAttributionItem(e)),
		author: list(a[1]).map((e) => readImageAuthor(e)),
	};
}

export function readLatLng(v: unknown): LatLng {
	const a = list(v);
	return {
		lat: num(a[2]),
		lng: num(a[3]),
	};
}

export function readAltitude(v: unknown): Altitude {
	const a = list(v);
	return {
		meters: num(a[0]),
	};
}

export function readPov(v: unknown): Pov {
	const a = list(v);
	return {
		heading: num(a[0]),
		tilt: num(a[1]),
		roll: num(a[2]),
	};
}

export function readLevel(v: unknown): Level {
	const a = list(v);
	return {
		id: num(a[0]),
		name: msg(a[2]) && readLocalizedText(a[2]),
		abbreviation: msg(a[3]) && readLocalizedText(a[3]),
	};
}

export function readPanoLocation(v: unknown): PanoLocation {
	const a = list(v);
	return {
		location: msg(a[0]) && readLatLng(a[0]),
		altitude: msg(a[1]) && readAltitude(a[1]),
		pov: msg(a[2]) && readPov(a[2]),
		level: msg(a[3]) && readLevel(a[3]),
		countryCode: str(a[4]),
	};
}

export function readPano(v: unknown): Pano {
	const a = list(v);
	return {
		key: msg(a[0]) && readImageKey(a[0]),
		location: msg(a[2]) && readPanoLocation(a[2]),
	};
}

export function readPanoRelations(v: unknown): PanoRelations {
	const a = list(v);
	return {
		pano: list(a[0]).map((e) => readPano(e)),
	};
}

export function readPanoLinkProperties(v: unknown): PanoLinkProperties {
	const a = list(v);
	return {
		heading: num(a[3]),
	};
}

export function readPanoLink(v: unknown): PanoLink {
	const a = list(v);
	return {
		target: num(a[0]),
		properties: msg(a[1]) && readPanoLinkProperties(a[1]),
	};
}

export function readPanoDate(v: unknown): PanoDate {
	const a = list(v);
	return {
		year: num(a[0]),
		month: num(a[1]),
		day: num(a[2]),
	};
}

export function readPanoTime(v: unknown): PanoTime {
	const a = list(v);
	return {
		target: num(a[0]),
		date: msg(a[1]) && readPanoDate(a[1]),
	};
}

export function readImageInformation(v: unknown): ImageInformation {
	const a = list(v);
	return {
		status: msg(a[0]) && readImageStatus(a[0]),
		location: msg(a[1]) && readPanoLocation(a[1]),
		relations: msg(a[3]) && readPanoRelations(a[3]),
		link: list(a[6]).map((e) => readPanoLink(e)),
		time: list(a[8]).map((e) => readPanoTime(e)),
	};
}

export function readDateSourceInfo(v: unknown): DateSourceInfo {
	const a = list(v);
	return {
		source: str(a[2]),
	};
}

export function readImageDate(v: unknown): ImageDate {
	const a = list(v);
	return {
		sourceInfo: msg(a[5]) && readDateSourceInfo(a[5]),
		date: msg(a[7]) && readPanoDate(a[7]),
	};
}
